package zhipu

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// flagshipTextModels enumerates Zhipu's flagship text-only chat models.
// Pricing comes from https://open.bigmodel.cn/pricing; metadata derives from
// https://docs.bigmodel.cn/cn/guide/start/model-overview and per-model spec pages.
// Last updated: 2026-06-13.
var flagshipTextModels = map[string]adaptor.ModelConfig{
	// GLM-5-Turbo: input [0,32K) ¥5/¥22, input [32K+) ¥7/¥26
	"glm-5-turbo": {
		Ratio:            5 * ratio.MilliTokensRmb,
		CompletionRatio:  22.0 / 5.0,
		CachedInputRatio: 1.2 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 7 * ratio.MilliTokensRmb, CompletionRatio: 26.0 / 7.0, CachedInputRatio: 1.8 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-5-Turbo: lobster-task-tuned high-performance base model with 200K context.",
	},
	// GLM-5: input [0,32K) ¥4/¥18, input [32K+) ¥6/¥22
	"glm-5": {
		Ratio:            4 * ratio.MilliTokensRmb,
		CompletionRatio:  18.0 / 4.0,
		CachedInputRatio: 1 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 6 * ratio.MilliTokensRmb, CompletionRatio: 22.0 / 6.0, CachedInputRatio: 1.5 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-5",
		Quantization:                "bf16",
		Description:                 "GLM-5: 754B agentic engineering flagship aligned with Claude Opus 4.5 on coding.",
	},
	// GLM-5.1: input [0,32K) ¥6/¥24, input [32K+) ¥8/¥28
	"glm-5.1": {
		Ratio:            6 * ratio.MilliTokensRmb,
		CompletionRatio:  24.0 / 6.0,
		CachedInputRatio: 1.3 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 8 * ratio.MilliTokensRmb, CompletionRatio: 28.0 / 8.0, CachedInputRatio: 2 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               200_000,
		MaxOutputTokens:             128_000,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-5.1",
		Quantization:                "bf16",
		Description:                 "GLM-5.1: 754B MoE agentic flagship (released 2026-04-07) with stronger coding aligned with Claude Opus 4.6, MCP integration, and 8-hour autonomous task execution; 200K context.",
	},
	// GLM-5.2: ¥8/¥28 per 1M input/output, ¥2 cached-input, 1M context
	"glm-5.2": {
		Ratio:                       8 * ratio.MilliTokensRmb,
		CompletionRatio:             28.0 / 8.0,
		CachedInputRatio:            2 * ratio.MilliTokensRmb,
		ContextLength:               1_000_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-5.2",
		Quantization:                "bf16",
		Description:                 "GLM-5.2: flagship long-task MoE coding model with Solid 1M lossless context and dual reasoning presets (High/Max); official API pricing ¥8/¥28 per 1M input/output, ¥2 cached-input.",
	},
	// GLM-4.7: input [0,32K) output [0,0.2M) ¥2/¥8; output [0.2M+) ¥3/¥14; input [32K,200K) ¥4/¥16
	"glm-4.7": {
		Ratio:            2 * ratio.MilliTokensRmb,
		CompletionRatio:  8.0 / 2.0,
		CachedInputRatio: 0.4 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 3 * ratio.MilliTokensRmb, CompletionRatio: 14.0 / 3.0, CachedInputRatio: 0.6 * ratio.MilliTokensRmb, InputTokenThreshold: 0},
			{Ratio: 4 * ratio.MilliTokensRmb, CompletionRatio: 16.0 / 4.0, CachedInputRatio: 0.8 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-4.7",
		Quantization:                "bf16",
		Description:                 "GLM-4.7: 358B agentic-coding flagship with interleaved thinking and 200K context.",
	},
	// GLM-4.7-FlashX: ¥0.5/¥3
	"glm-4.7-flashx": {
		Ratio:                       0.5 * ratio.MilliTokensRmb,
		CompletionRatio:             3.0 / 0.5,
		CachedInputRatio:            0.1 * ratio.MilliTokensRmb,
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4.7-FlashX: lightweight high-throughput sibling of GLM-4.7 with 200K context.",
	},
	// GLM-4.7-Flash (free)
	"glm-4.7-flash": {
		Ratio:                       0,
		CompletionRatio:             1,
		CachedInputRatio:            0,
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-4.7-Flash",
		Quantization:                "bf16",
		Description:                 "GLM-4.7-Flash: free 31B open-weight base model with 200K context.",
	},
	// GLM-4.6: same tiered pricing as GLM-4.7
	"glm-4.6": {
		Ratio:            2 * ratio.MilliTokensRmb,
		CompletionRatio:  8.0 / 2.0,
		CachedInputRatio: 0.4 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 3 * ratio.MilliTokensRmb, CompletionRatio: 14.0 / 3.0, CachedInputRatio: 0.6 * ratio.MilliTokensRmb, InputTokenThreshold: 0},
			{Ratio: 4 * ratio.MilliTokensRmb, CompletionRatio: 16.0 / 4.0, CachedInputRatio: 0.8 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               200_000,
		MaxOutputTokens:             131_072,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-4.6",
		Quantization:                "bf16",
		Description:                 "GLM-4.6: 355B/32B-active MoE coding model with 200K context, aligned with Claude Sonnet 4.",
	},
	// GLM-4.5-Air: input [0,32K) output [0,0.2M) ¥0.8/¥2; output [0.2M+) ¥0.8/¥6; input [32K,128K) ¥1.2/¥8
	"glm-4.5-air": {
		Ratio:            0.8 * ratio.MilliTokensRmb,
		CompletionRatio:  2.0 / 0.8,
		CachedInputRatio: 0.16 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 0.8 * ratio.MilliTokensRmb, CompletionRatio: 6.0 / 0.8, CachedInputRatio: 0.16 * ratio.MilliTokensRmb, InputTokenThreshold: 0},
			{Ratio: 1.2 * ratio.MilliTokensRmb, CompletionRatio: 8.0 / 1.2, CachedInputRatio: 0.24 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               131_072,
		MaxOutputTokens:             98_304,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-4.5-Air",
		Quantization:                "bf16",
		Description:                 "GLM-4.5-Air: 106B/12B-active MoE cost-efficient agentic model with 128K context.",
	},
	// GLM-4.5
	"glm-4.5": {
		Ratio:            2 * ratio.MilliTokensRmb,
		CompletionRatio:  8.0 / 2.0,
		CachedInputRatio: 0.4 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 3 * ratio.MilliTokensRmb, CompletionRatio: 14.0 / 3.0, CachedInputRatio: 0.6 * ratio.MilliTokensRmb, InputTokenThreshold: 0},
			{Ratio: 4 * ratio.MilliTokensRmb, CompletionRatio: 16.0 / 4.0, CachedInputRatio: 0.8 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               131_072,
		MaxOutputTokens:             98_304,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "zai-org/GLM-4.5",
		Quantization:                "bf16",
		Description:                 "GLM-4.5: 355B/32B-active MoE flagship for agent applications with hybrid thinking. (slated for retirement, along with GLM-4.5-X, in favor of GLM-4.7)",
	},
	// GLM-4.5-X
	"glm-4.5-x": {
		Ratio:            8 * ratio.MilliTokensRmb,
		CompletionRatio:  2,
		CachedInputRatio: 1.6 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 12 * ratio.MilliTokensRmb, CompletionRatio: 32.0 / 12.0, CachedInputRatio: 2.4 * ratio.MilliTokensRmb, InputTokenThreshold: 0},
			{Ratio: 16 * ratio.MilliTokensRmb, CompletionRatio: 64.0 / 16.0, CachedInputRatio: 3.2 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               131_072,
		MaxOutputTokens:             98_304,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4.5-X: high-performance speed-optimized variant of GLM-4.5 (slated for retirement).",
	},
	// GLM-4.5-AirX
	"glm-4.5-airx": {
		Ratio:            4 * ratio.MilliTokensRmb,
		CompletionRatio:  16.0 / 4.0,
		CachedInputRatio: 0.8 * ratio.MilliTokensRmb,
		Tiers: []adaptor.ModelRatioTier{
			{Ratio: 8 * ratio.MilliTokensRmb, CompletionRatio: 32.0 / 8.0, CachedInputRatio: 1.6 * ratio.MilliTokensRmb, InputTokenThreshold: 32},
		},
		ContextLength:               131_072,
		MaxOutputTokens:             98_304,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4.5-AirX: speed-optimized GLM-4.5-Air with 100+ tokens/s generation throughput.",
	},
}

// languageModels enumerates flat-priced language-only chat models.
var languageModels = map[string]adaptor.ModelConfig{
	"glm-4-plus": {
		Ratio:                       5 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-Plus: legacy high-intelligence text model.",
	},
	"glm-4-air": {
		Ratio:                       0.5 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-Air: cost-efficient legacy text model.",
	},
	"glm-4-airx": {
		Ratio:                       10 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               8_192,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-AirX: speed-optimized GLM-4-Air with reduced 8K context window.",
	},
	"glm-4-flashx-250414": {
		Ratio:                       0.1 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             16_384,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-FlashX-250414: high-throughput Flash variant with 128K context.",
	},
	"glm-4-long": {
		Ratio:                       1 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               1_000_000,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-Long: 1M-context model designed for very long inputs and memory-style tasks.",
	},
	"glm-4-assistant": {
		Ratio:                       5 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-Assistant: assistant-tuned variant for agentic application stacks.",
	},
	"glm-4-flash-250414": {
		Ratio:                       0,
		CompletionRatio:             1,
		CachedInputRatio:            0,
		ContextLength:               131_072,
		MaxOutputTokens:             16_384,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4-Flash-250414: free Flash text model with 128K context and tool calling.",
	},
	"glm-4.5-flash": {
		Ratio:                       0,
		CompletionRatio:             1,
		CachedInputRatio:            0,
		ContextLength:               131_072,
		MaxOutputTokens:             98_304,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-4.5-Flash: free GLM-4.5 sibling with thinking mode (slated for retirement) (deprecated; scheduled for retirement). RETIRED 2026-01-30.",
	},
	"glm-4-flash": {
		Ratio:                       0,
		CompletionRatio:             1,
		CachedInputRatio:            0,
		ContextLength:               131_072,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           commonChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "THUDM/glm-4-9b-chat",
		Quantization:                "bf16",
		Description:                 "GLM-4-Flash: legacy free text model; open weights on HuggingFace as glm-4-9b-chat.",
	},
}

// reasoningModels enumerates reasoning-only models (GLM-Z1 family) and visual reasoners.
var reasoningModels = map[string]adaptor.ModelConfig{
	"glm-z1-air": {
		Ratio:                       0.5 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             32_768,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           []string{"reasoning"},
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GLM-Z1-Air: cost-efficient reasoning model (deprecated 2025-11-15) (RETIRED 2025-11-15).",
	},
	"glm-z1-airx": {
		Ratio:                       5 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32_768,
		MaxOutputTokens:             32_768,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           []string{"reasoning"},
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GLM-Z1-AirX: speed-optimized reasoning model (deprecated 2025-11-15) (RETIRED 2025-11-15).",
	},
	"glm-z1-flashx": {
		Ratio:                       0.1 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             32_768,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           []string{"reasoning"},
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GLM-Z1-FlashX: high-throughput reasoning Flash variant (deprecated 2025-11-15) (RETIRED 2025-11-15).",
	},
	"glm-4.1v-thinking-flashx": {
		Ratio:                       2 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               65_536,
		MaxOutputTokens:             16_384,
		InputModalities:             textImageInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "THUDM/GLM-4.1V-9B-Thinking",
		Quantization:                "bf16",
		Description:                 "GLM-4.1V-Thinking-FlashX: lightweight visual reasoning model with chain-of-thought.",
	},
	"glm-4.1v-thinking-flash": {
		Ratio:                       0,
		CompletionRatio:             1,
		CachedInputRatio:            0,
		ContextLength:               65_536,
		MaxOutputTokens:             16_384,
		InputModalities:             textImageInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           reasoningChatFeatures(),
		SupportedSamplingParameters: chatSamplingParameters(),
		HuggingFaceID:               "THUDM/GLM-4.1V-9B-Thinking",
		Quantization:                "bf16",
		Description:                 "GLM-4.1V-Thinking-Flash: free visual reasoning model with multi-step analysis.",
	},
}

// legacyModels enumerates older Zhipu chat models retained for backward compatibility.
var legacyModels = map[string]adaptor.ModelConfig{
	"glm-3-turbo": {
		Ratio:                       0.005 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131_072,
		MaxOutputTokens:             4_096,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: chatSamplingParameters(),
		Description:                 "GLM-3-Turbo: legacy generation model retained for backward compatibility.",
	},
	"glm-zero-preview": {
		Ratio:                       0.7 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               16_384,
		MaxOutputTokens:             12_288,
		InputModalities:             textInput(),
		OutputModalities:            textOutput(),
		SupportedFeatures:           []string{"reasoning"},
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GLM-Zero-Preview: early reasoning preview model (precursor to GLM-Z1).",
	},
}
