package model

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/Laisky/one-api/common"
)

// T11 — mixed-version Redis cache payload compatibility.
//
// During a rolling deploy the pre-refactor and post-refactor binaries share the
// same Redis instance and the same cache keys ("user_obj:<id>", "token:<key>"),
// so each binary must be able to read payloads written by the other. §3.3.5 of
// docs/proposals/20260714_boundary-response-dtos.md asserts this is safe because
// "cache payloads only ever gain keys". The fixtures and assertions below turn
// that assertion into a measurement.
//
// MEASURED KEY-SET DELTA (fixtures generated by the real pre-refactor binary at
// git 6ebe28a5 and compared against the real post-refactor cache writers):
//
//	user_obj:<id>  pre  = 25 keys (every model.User field except "totp_secret",
//	                     which the pre-refactor writer scrubbed to "" and whose
//	                     tag carried `omitempty`)
//	               post = 22 keys
//	               post \ pre = {}                                    (nothing gained)
//	               pre \ post = {"password", "access_token", "verification_code"}
//
//	token:<key>    pre  = post = 17 keys; delta is EMPTY in both directions
//	                     (the pre-refactor writer already used `type plainToken
//	                     Token`, i.e. the same raw field set the post-refactor
//	                     writer emits — so the proposal's "(for Token) gains
//	                     id/user_id" note is describing a gain that never applied
//	                     to the cache path).
//
// So §3.3.5's literal claim ("payloads only ever gain keys") DOES NOT HOLD: the
// user payload strictly SHRINKS by three keys. The safety conclusion it draws
// nevertheless holds, for a different and stronger reason — each dropped key was
// guaranteed to carry the empty string in every pre-refactor payload:
//
//   - "password" and "access_token" were explicitly scrubbed to "" by
//     CacheGetUserById before marshaling (see model/cache.go at 6ebe28a5).
//   - "verification_code" is `gorm:"-:all"`, so the GetUserById row that feeds
//     the cache can never populate it (asserted mechanically in
//     TestMixedVersionUserCache_VerificationCodeWasNeverPersistable).
//
// A pre-refactor reader that finds these keys missing therefore decodes exactly
// the zero value it would have decoded from the key being present-and-empty:
// behaviour is identical, and no cache flush is required. The direction the
// proposal actually cared about — the #353 invariant that "id" survives the
// round-trip — holds in both directions, because both writers emit it.
//
// Post-refactor the three dropped keys are `json:"-"`, which additionally means
// a legacy payload's secret values CANNOT be re-hydrated into a model.User by
// the new binary (proved below with a fixture that deliberately carries a
// non-empty "verification_code").

const (
	preRefactorUserFixture  = "testdata/cache_user_pre_refactor.json"
	preRefactorTokenFixture = "testdata/cache_token_pre_refactor.json"
)

// preRefactorUser is a byte-faithful replica of model.User as it existed at git
// 6ebe28a5 (the last pre-refactor commit). It stands in for "the old binary's
// reader" so the current->old direction can be exercised for real rather than
// argued. TestMixedVersionUserCache_ReplicaMatchesPreRefactorFixture pins the
// replica against the fixture that the real old binary produced, so drift here
// fails loudly instead of silently weakening the test.
type preRefactorUser struct {
	Id               int             `json:"id"`
	UUID             string          `json:"uuid"`
	Username         string          `json:"username"`
	Password         string          `json:"password"`
	DisplayName      string          `json:"display_name"`
	Role             int             `json:"role"`
	Status           int             `json:"status"`
	Email            string          `json:"email"`
	GitHubId         string          `json:"github_id"`
	WeChatId         string          `json:"wechat_id"`
	LarkId           string          `json:"lark_id"`
	OidcId           string          `json:"oidc_id"`
	VerificationCode string          `json:"verification_code"`
	AccessToken      string          `json:"access_token"`
	TotpSecret       string          `json:"totp_secret,omitempty"`
	Quota            int64           `json:"quota"`
	UsedQuota        int64           `json:"used_quota"`
	RequestCount     int             `json:"request_count"`
	Group            string          `json:"group"`
	AffCode          string          `json:"aff_code"`
	InviterId        int             `json:"inviter_id"`
	InviterUUID      *string         `json:"inviter_uuid"`
	MCPToolBlacklist JSONStringSlice `json:"mcp_tool_blacklist"`
	Metadata         UserMetadata    `json:"metadata"`
	CreatedAt        int64           `json:"created_at"`
	UpdatedAt        int64           `json:"updated_at"`
}

// setupMixedVersionCacheTest wires the same miniredis-backed runtime as
// setupUserObjCacheTest and additionally pins the token cache TTL, so both
// "user_obj:<id>" and "token:<key>" entries survive between calls.
//
// Parameters:
//   - t: the testing handle; cleanups restore every global it mutates.
//
// Return values:
//   - context.Context: context to pass to the cache functions under test.
func setupMixedVersionCacheTest(t *testing.T) context.Context {
	t.Helper()
	ctx := setupUserObjCacheTest(t)

	originalTokenTTL := TokenCacheSeconds
	TokenCacheSeconds = 300
	t.Cleanup(func() { TokenCacheSeconds = originalTokenTTL })

	return ctx
}

// loadJSONFixture reads a testdata fixture and decodes it into a generic map.
//
// Parameters:
//   - t: the testing handle.
//   - path: fixture path relative to the model package directory.
//
// Return values:
//   - []byte: the raw fixture bytes, exactly as the pre-refactor binary wrote them.
//   - map[string]any: the decoded payload, for key-set and value assertions.
func loadJSONFixture(t *testing.T, path string) ([]byte, map[string]any) {
	t.Helper()
	raw, err := os.ReadFile(path)
	require.NoError(t, err, "fixture %s must exist", path)
	var decoded map[string]any
	require.NoError(t, json.Unmarshal(raw, &decoded), "fixture %s must be valid JSON", path)
	return raw, decoded
}

// jsonKeySet returns the sorted top-level key set of a JSON object payload.
//
// Parameters:
//   - t: the testing handle.
//   - raw: a JSON object payload.
//
// Return values:
//   - []string: the sorted top-level keys.
func jsonKeySet(t *testing.T, raw []byte) []string {
	t.Helper()
	var decoded map[string]any
	require.NoError(t, json.Unmarshal(raw, &decoded))
	keys := make([]string, 0, len(decoded))
	for k := range decoded {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// keysMissingFrom returns the elements of want that are absent from got.
//
// Parameters:
//   - want: the reference key set (what the old reader depended on).
//   - got: the key set actually produced.
//
// Return values:
//   - []string: the keys present in want but not in got.
func keysMissingFrom(want, got []string) []string {
	present := make(map[string]struct{}, len(got))
	for _, k := range got {
		present[k] = struct{}{}
	}
	var missing []string
	for _, k := range want {
		if _, ok := present[k]; !ok {
			missing = append(missing, k)
		}
	}
	return missing
}

// TestMixedVersionUserCache_ReplicaMatchesPreRefactorFixture guards the
// preRefactorUser replica against drift: it rebuilds the exact fixture value
// through the exact pre-refactor cache-write path (`type plainUser User` + the
// explicit Password/AccessToken/TotpSecret scrub) and requires byte-equivalence
// with the fixture the real pre-refactor binary emitted. If this fails, the
// replica is no longer a valid stand-in for the old reader and every conclusion
// drawn from it below is void.
func TestMixedVersionUserCache_ReplicaMatchesPreRefactorFixture(t *testing.T) {
	fixtureBytes, _ := loadJSONFixture(t, preRefactorUserFixture)

	inviterUUID := "018f0000-0000-7000-8000-000000000009"
	replica := preRefactorUser{
		Id:               42,
		UUID:             "018f0000-0000-7000-8000-000000000001",
		Username:         "alice",
		Password:         "$2a$10$bcrypthashsecret",
		DisplayName:      "Alice Example",
		Role:             RoleAdminUser,
		Status:           UserStatusEnabled,
		Email:            "alice@example.com",
		GitHubId:         "gh-alice",
		WeChatId:         "wx-alice",
		LarkId:           "lark-alice",
		OidcId:           "oidc-alice",
		VerificationCode: "verif-code",
		AccessToken:      "access-token-secret-000000000000",
		TotpSecret:       "JBSWY3DPEHPK3PXP",
		Quota:            98765,
		UsedQuota:        4321,
		RequestCount:     17,
		Group:            "vip",
		AffCode:          "AFF123",
		InviterId:        7,
		InviterUUID:      &inviterUUID,
		MCPToolBlacklist: JSONStringSlice{"tool_a", "tool_b"},
		Metadata:         UserMetadata{PasswordLocked: true},
		CreatedAt:        1700000000000,
		UpdatedAt:        1700000001000,
	}
	// Verbatim reproduction of CacheGetUserById's pre-refactor scrub.
	replica.Password = ""
	replica.AccessToken = ""
	replica.TotpSecret = ""

	got, err := json.Marshal(replica)
	require.NoError(t, err)
	require.JSONEq(t, string(fixtureBytes), string(got),
		"preRefactorUser replica drifted from the payload the real pre-refactor binary writes")
}

// TestMixedVersionUserCache_VerificationCodeWasNeverPersistable mechanically
// backs the safety argument for the one dropped key whose fixture value is
// non-empty. "verification_code" disappears from the post-refactor payload, but
// the pre-refactor payload could only ever carry "" for it in production,
// because the field is gorm:"-:all" and the cached object is always sourced from
// a GetUserById database read. Losing a key that was structurally always empty
// cannot change what an old reader decodes.
func TestMixedVersionUserCache_VerificationCodeWasNeverPersistable(t *testing.T) {
	field, ok := reflect.TypeOf(User{}).FieldByName("VerificationCode")
	require.True(t, ok)
	require.Equal(t, "-:all", field.Tag.Get("gorm"),
		"VerificationCode must stay non-persisted; otherwise the pre-refactor cache payload could have carried a real code and dropping the key would lose data")
}

// TestMixedVersionUserCache_OldPayloadReadByCurrentCode proves the
// old-payload -> new-binary direction through the REAL CacheGetUserById path:
// a payload produced by the pre-refactor binary is planted in miniredis under
// the production key and read back by the current code.
//
// The user id used here does not exist in the test database, so GetUserById
// would fail — a NoError result therefore proves the value came from the cache
// entry, not from a silent DB fallback.
func TestMixedVersionUserCache_OldPayloadReadByCurrentCode(t *testing.T) {
	ctx := setupMixedVersionCacheTest(t)

	const cachedId = 987654321
	_, fixture := loadJSONFixture(t, preRefactorUserFixture)

	// Sanity: the fixture is genuinely a legacy payload — it carries the three
	// keys the current struct no longer emits, and one of them is non-empty.
	require.Contains(t, fixture, "password")
	require.Contains(t, fixture, "access_token")
	require.Contains(t, fixture, "verification_code")
	require.Equal(t, "verif-code", fixture["verification_code"],
		"fixture must carry a non-empty legacy secret so the drop is observable")

	fixture["id"] = cachedId
	// An unknown key a hypothetical newer/other writer might add: the reader must
	// tolerate it rather than fail the whole entry.
	fixture["some_future_key"] = map[string]any{"nested": true}
	planted, err := json.Marshal(fixture)
	require.NoError(t, err)

	cacheKey := fmt.Sprintf("user_obj:%d", cachedId)
	require.NoError(t, common.RedisSet(ctx, cacheKey, string(planted), 300*time.Second))

	got, err := CacheGetUserById(ctx, cachedId)
	require.NoError(t, err,
		"legacy payload must decode; user %d has no DB row, so success proves the cache path served it", cachedId)
	require.NotNil(t, got)

	// The #353 invariant: the integer Id survives a cross-version cache hit.
	require.Equal(t, cachedId, got.Id, "legacy cache payload must still preserve the internal integer Id")

	// Every non-secret field the old writer emitted must land in the new struct.
	require.Equal(t, "018f0000-0000-7000-8000-000000000001", got.UUID)
	require.Equal(t, "alice", got.Username)
	require.Equal(t, "Alice Example", got.DisplayName)
	require.Equal(t, RoleAdminUser, got.Role)
	require.Equal(t, UserStatusEnabled, got.Status)
	require.Equal(t, "alice@example.com", got.Email)
	require.Equal(t, "gh-alice", got.GitHubId)
	require.Equal(t, "wx-alice", got.WeChatId)
	require.Equal(t, "lark-alice", got.LarkId)
	require.Equal(t, "oidc-alice", got.OidcId)
	require.EqualValues(t, 98765, got.Quota)
	require.EqualValues(t, 4321, got.UsedQuota)
	require.Equal(t, 17, got.RequestCount)
	require.Equal(t, "vip", got.Group)
	require.Equal(t, "AFF123", got.AffCode)
	require.Equal(t, 7, got.InviterId)
	require.NotNil(t, got.InviterUUID)
	require.Equal(t, "018f0000-0000-7000-8000-000000000009", *got.InviterUUID)
	require.Equal(t, JSONStringSlice{"tool_a", "tool_b"}, got.MCPToolBlacklist)
	require.Equal(t, UserMetadata{PasswordLocked: true}, got.Metadata)
	require.EqualValues(t, 1700000000000, got.CreatedAt)
	require.EqualValues(t, 1700000001000, got.UpdatedAt)

	// The legacy secret keys are `json:"-"` now: they are ignored, not decoded.
	// Note "verification_code" is non-empty in the payload and STILL does not
	// reach the struct — legacy secrets cannot be re-hydrated by the new binary.
	require.Empty(t, got.Password, "legacy \"password\" key must not populate the field")
	require.Empty(t, got.AccessToken, "legacy \"access_token\" key must not populate the field")
	require.Empty(t, got.TotpSecret, "legacy payload must not populate the TOTP secret")
	require.Empty(t, got.VerificationCode, "legacy \"verification_code\" key must not populate the field")
}

// TestMixedVersionUserCache_CurrentPayloadReadByPreRefactorReader proves the
// new-payload -> old-binary direction: the current CacheGetUserById writes a
// real entry to miniredis, and the pre-refactor reader replica decodes it.
//
// It asserts the measured key-set delta explicitly (rather than trusting
// §3.3.5's "keys only grow"), and requires that every key the old reader
// depended on for a non-zero value is still present.
func TestMixedVersionUserCache_CurrentPayloadReadByPreRefactorReader(t *testing.T) {
	ctx := setupMixedVersionCacheTest(t)

	inviterUUID := "018f0000-0000-7000-8000-000000000009"
	user := &User{
		Username:         fmt.Sprintf("test-mixedver-%d", time.Now().UnixNano()),
		Password:         "testpassword12345",
		DisplayName:      "Alice Example",
		Role:             RoleAdminUser,
		Status:           UserStatusEnabled,
		Email:            fmt.Sprintf("test-mixedver-%d@example.com", time.Now().UnixNano()),
		GitHubId:         "gh-alice",
		WeChatId:         "wx-alice",
		LarkId:           "lark-alice",
		OidcId:           "oidc-alice",
		AccessToken:      fmt.Sprintf("test-mixedver-token-%d", time.Now().UnixNano()),
		TotpSecret:       "JBSWY3DPEHPK3PXP",
		Quota:            98765,
		UsedQuota:        4321,
		RequestCount:     17,
		Group:            "vip",
		AffCode:          fmt.Sprintf("AFF%d", time.Now().UnixNano()),
		InviterId:        7,
		InviterUUID:      &inviterUUID,
		MCPToolBlacklist: JSONStringSlice{"tool_a", "tool_b"},
		Metadata:         UserMetadata{PasswordLocked: true},
	}
	require.NoError(t, DB.Create(user).Error)
	require.NotZero(t, user.Id)
	t.Cleanup(func() { DB.Exec("DELETE FROM users WHERE id = ?", user.Id) })

	// Cache miss -> the current binary writes the entry.
	_, err := CacheGetUserById(ctx, user.Id)
	require.NoError(t, err)
	rawPayload, err := common.RedisGet(ctx, fmt.Sprintf("user_obj:%d", user.Id))
	require.NoError(t, err, "current binary must have populated the cache")

	// --- key-set delta, measured against the real pre-refactor fixture ---
	fixtureBytes, _ := loadJSONFixture(t, preRefactorUserFixture)
	oldKeys := jsonKeySet(t, fixtureBytes)
	newKeys := jsonKeySet(t, []byte(rawPayload))

	require.Empty(t, keysMissingFrom(newKeys, oldKeys),
		"new payload gained keys the pre-refactor fixture lacks; update the §3.3.5 delta note above")
	require.Equal(t, []string{"access_token", "password", "verification_code"},
		keysMissingFrom(oldKeys, newKeys),
		"exactly three always-empty keys may disappear; ANY other loss is a real mixed-version regression")

	// The key the incident was about is present in both versions.
	require.Contains(t, newKeys, "id", "#353: the cached payload must carry the integer id")

	// --- the old reader actually decodes the new payload ---
	var oldReader preRefactorUser
	require.NoError(t, json.Unmarshal([]byte(rawPayload), &oldReader),
		"pre-refactor reader must not fail on the current payload")

	require.Equal(t, user.Id, oldReader.Id, "#353 invariant across versions: Id survives for the old reader too")
	require.Equal(t, user.UUID, oldReader.UUID)
	require.Equal(t, user.Username, oldReader.Username)
	require.Equal(t, user.DisplayName, oldReader.DisplayName)
	require.Equal(t, RoleAdminUser, oldReader.Role)
	require.Equal(t, UserStatusEnabled, oldReader.Status)
	require.Equal(t, user.Email, oldReader.Email)
	require.Equal(t, "gh-alice", oldReader.GitHubId)
	require.Equal(t, "wx-alice", oldReader.WeChatId)
	require.Equal(t, "lark-alice", oldReader.LarkId)
	require.Equal(t, "oidc-alice", oldReader.OidcId)
	require.EqualValues(t, 98765, oldReader.Quota)
	require.EqualValues(t, 4321, oldReader.UsedQuota)
	require.Equal(t, 17, oldReader.RequestCount)
	require.Equal(t, "vip", oldReader.Group)
	require.Equal(t, user.AffCode, oldReader.AffCode)
	require.Equal(t, 7, oldReader.InviterId)
	require.NotNil(t, oldReader.InviterUUID)
	require.Equal(t, inviterUUID, *oldReader.InviterUUID)
	require.Equal(t, JSONStringSlice{"tool_a", "tool_b"}, oldReader.MCPToolBlacklist)
	require.Equal(t, UserMetadata{PasswordLocked: true}, oldReader.Metadata)
	require.NotZero(t, oldReader.CreatedAt)
	require.NotZero(t, oldReader.UpdatedAt)

	// The three dropped keys decode to exactly what the pre-refactor payload's
	// scrubbed/never-persisted values would have decoded to: the empty string.
	// This is why the shrink is behaviourally inert for the old reader.
	require.Empty(t, oldReader.Password)
	require.Empty(t, oldReader.AccessToken)
	require.Empty(t, oldReader.TotpSecret)
	require.Empty(t, oldReader.VerificationCode)
}

// TestMixedVersionTokenCache_OldPayloadReadByCurrentCode proves the
// old-payload -> new-binary direction for "token:<key>" through the real
// CacheGetTokenByKey path. No matching DB row exists, so a NoError result can
// only come from the planted cache entry.
//
// The load-bearing detail: the pre-refactor writer used `type plainToken Token`
// to keep the RAW (unprefixed) key in Redis. The post-refactor reader must still
// read that raw key back verbatim — the response-time "sk-" prefix now lives in
// Token.ToResponse, not in json.Marshal.
func TestMixedVersionTokenCache_OldPayloadReadByCurrentCode(t *testing.T) {
	ctx := setupMixedVersionCacheTest(t)

	_, fixture := loadJSONFixture(t, preRefactorTokenFixture)
	tokenKey, ok := fixture["key"].(string)
	require.True(t, ok)

	// Tolerate a key the current struct does not know about.
	fixture["some_future_key"] = "ignored"
	planted, err := json.Marshal(fixture)
	require.NoError(t, err)

	require.NoError(t, common.RedisSet(ctx, fmt.Sprintf("token:%s", tokenKey), string(planted), 300*time.Second))

	got, err := CacheGetTokenByKey(ctx, tokenKey)
	require.NoError(t, err, "legacy token payload must decode; no DB row exists, so this proves the cache path")
	require.NotNil(t, got)

	require.Equal(t, 99, got.Id, "legacy token payload must preserve the internal integer Id")
	require.Equal(t, 42, got.UserId, "legacy token payload must preserve the internal user_id")
	require.Equal(t, "018f0000-0000-7000-8000-000000000002", got.UUID)
	require.NotNil(t, got.UserUUID)
	require.Equal(t, "018f0000-0000-7000-8000-000000000001", *got.UserUUID)
	require.Equal(t, tokenKey, got.Key, "the cached key must round-trip RAW (unprefixed)")
	require.Equal(t, TokenStatusEnabled, got.Status)
	require.Equal(t, "primary", got.Name)
	require.EqualValues(t, 1700000000, got.CreatedTime)
	require.EqualValues(t, 1700000500, got.AccessedTime)
	require.EqualValues(t, -1, got.ExpiredTime)
	require.EqualValues(t, 500000, got.RemainQuota)
	require.False(t, got.UnlimitedQuota)
	require.EqualValues(t, 1234, got.UsedQuota)
	require.EqualValues(t, 1700000000000, got.CreatedAt)
	require.EqualValues(t, 1700000001000, got.UpdatedAt)
	require.NotNil(t, got.Models)
	require.Equal(t, "gpt-4o,claude-opus-4-8", *got.Models)
	require.NotNil(t, got.Subnet)
	require.Equal(t, "10.0.0.0/8", *got.Subnet)
}

// TestMixedVersionTokenCache_CurrentPayloadReadByPreRefactorReader proves the
// new-payload -> old-binary direction for "token:<key>": the current
// CacheGetTokenByKey populates the entry on a miss, and the payload's key set is
// required to be IDENTICAL to the pre-refactor fixture's (the token cache never
// went through Token.MarshalJSON, so retiring it changed nothing here).
func TestMixedVersionTokenCache_CurrentPayloadReadByPreRefactorReader(t *testing.T) {
	ctx := setupMixedVersionCacheTest(t)

	models := "gpt-4o,claude-opus-4-8"
	subnet := "10.0.0.0/8"
	token := &Token{
		UserId:         42,
		Key:            fmt.Sprintf("%048d", time.Now().UnixNano()),
		Status:         TokenStatusEnabled,
		Name:           fmt.Sprintf("test-mixedver-%d", time.Now().UnixNano()),
		CreatedTime:    1700000000,
		AccessedTime:   1700000500,
		ExpiredTime:    -1,
		RemainQuota:    500000,
		UnlimitedQuota: false,
		UsedQuota:      1234,
		Models:         &models,
		Subnet:         &subnet,
	}
	require.NoError(t, DB.Create(token).Error)
	require.NotZero(t, token.Id)
	t.Cleanup(func() { DB.Exec("DELETE FROM tokens WHERE id = ?", token.Id) })

	// Cache miss -> the current binary writes the entry.
	_, err := CacheGetTokenByKey(ctx, token.Key)
	require.NoError(t, err)
	rawPayload, err := common.RedisGet(ctx, fmt.Sprintf("token:%s", token.Key))
	require.NoError(t, err, "current binary must have populated the token cache")

	fixtureBytes, _ := loadJSONFixture(t, preRefactorTokenFixture)
	oldKeys := jsonKeySet(t, fixtureBytes)
	newKeys := jsonKeySet(t, []byte(rawPayload))
	require.Equal(t, oldKeys, newKeys,
		"the token cache payload key set must be unchanged across the refactor")

	var oldReader struct {
		Id     int    `json:"id"`
		UserId int    `json:"user_id"`
		Key    string `json:"key"`
		Status int    `json:"status"`
	}
	require.NoError(t, json.Unmarshal([]byte(rawPayload), &oldReader),
		"pre-refactor reader must not fail on the current token payload")
	require.Equal(t, token.Id, oldReader.Id)
	require.Equal(t, 42, oldReader.UserId)
	require.Equal(t, token.Key, oldReader.Key, "the raw key must still be cached unprefixed for the old reader")
	require.Equal(t, TokenStatusEnabled, oldReader.Status)
}
