package model

import (
	"context"
	"strconv"
	"testing"

	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// TestConditionalUpdateBindBudgetArithmetic covers UUID-A12: the calculated update chunk for the
// owned-UUID (3 binds/row), one-FK (5 binds/row), and two-condition token-name (7 binds/row)
// shapes stays at or below the 900-bind budget while never exceeding the configured row limit.
func TestConditionalUpdateBindBudgetArithmetic(t *testing.T) {
	t.Run("binds per row", func(t *testing.T) {
		require.Equal(t, 3, uuidConditionalBindsPerRow(0), "an owned-uuid row spends id, value and where-id")
		require.Equal(t, 5, uuidConditionalBindsPerRow(1), "a one-fk row rechecks one observed column")
		require.Equal(t, 7, uuidConditionalBindsPerRow(2), "a token-name row rechecks user_id and token_name")
	})

	t.Run("chunk size per shape", func(t *testing.T) {
		for _, testCase := range []struct {
			name       string
			conditions int
			wantBinds  int
			wantChunk  int
		}{
			{name: "owned uuid", conditions: 0, wantBinds: 3, wantChunk: 200},
			{name: "one fk", conditions: 1, wantBinds: 5, wantChunk: 180},
			{name: "token name", conditions: 2, wantBinds: 7, wantChunk: 128},
		} {
			testCase := testCase
			t.Run(testCase.name, func(t *testing.T) {
				bindsPerRow := uuidConditionalBindsPerRow(testCase.conditions)
				require.Equal(t, testCase.wantBinds, bindsPerRow)

				chunk := uuidChunkSize(uuidUpdateRowLimit, bindsPerRow, 0)
				require.Equal(t, testCase.wantChunk, chunk)
				require.GreaterOrEqual(t, chunk, 1, "a chunk always carries at least one row")
				require.LessOrEqual(t, chunk, uuidUpdateRowLimit, "a chunk never exceeds the configured limit")
				require.LessOrEqual(t, chunk*bindsPerRow, uuidBindBudget, "a chunk never exceeds the bind budget")
				// One more row would breach the budget only where the budget, not the
				// configured limit, is the binding constraint.
				if chunk < uuidUpdateRowLimit {
					require.Greater(t, (chunk+1)*bindsPerRow, uuidBindBudget, "the chunk must be the largest bind-safe size")
				}
			})
		}
	})

	t.Run("fixed binds are reserved", func(t *testing.T) {
		chunk := uuidChunkSize(uuidUpdateRowLimit, 7, 100)
		require.LessOrEqual(t, chunk, (uuidBindBudget-100)/7, "fixed binds must shrink the per-row budget")
		require.Equal(t, 114, chunk)
		require.LessOrEqual(t, chunk*7+100, uuidBindBudget)
	})

	t.Run("degenerate inputs stay usable", func(t *testing.T) {
		require.Equal(t, 1, uuidChunkSize(uuidUpdateRowLimit, uuidBindBudget+1, 0),
			"an oversized row still yields a one-row chunk")
		require.Equal(t, 1, uuidChunkSize(uuidUpdateRowLimit, 5, uuidBindBudget),
			"an exhausted fixed budget still yields a one-row chunk")
		require.Equal(t, uuidUpdateRowLimit, uuidChunkSize(uuidUpdateRowLimit, 0, 0),
			"a bind-free statement falls back to the configured limit")
	})
}

// TestConditionalUpdateStatementBindCount covers UUID-A12: the bind count of the statements
// actually generated by applyConditionalStringColumnRows — not just the chunking arithmetic —
// stays at or below the 900-bind budget for all three condition shapes.
func TestConditionalUpdateStatementBindCount(t *testing.T) {
	db, _ := newUnifiedTestTopology(t)
	const driven = 200
	seedUUIDBatchUsers(t, db, driven)
	require.NoError(t, db.Exec("INSERT INTO channels (id, type, name, models, config) VALUES (1, 1, 'primary', 'gpt-4o', '{}')").Error)
	seedUUIDBatchLogs(t, db, driven)

	recorder := installUUIDBatchUpdateBindRecorder(t, db)

	for _, testCase := range []struct {
		name   string
		table  string
		column string
		values []uuidConditionalValue
	}{
		{name: "owned uuid", table: "users", column: "uuid", values: uuidBatchOwnedValues(driven)},
		{name: "one fk", table: "users", column: "inviter_uuid", values: uuidBatchInviterValues(driven)},
		{name: "token name", table: "logs", column: "token_uuid", values: uuidBatchTokenNameValues(driven)},
	} {
		testCase := testCase
		t.Run(testCase.name, func(t *testing.T) {
			recorder.reset()
			updated, err := applyConditionalStringColumnRows(context.Background(), db, testCase.table, testCase.column, testCase.values)
			require.NoError(t, err)
			require.Equal(t, driven, updated)

			observed := recorder.observations()
			require.NotEmpty(t, observed, "the update must actually reach the database")
			for i, binds := range observed {
				require.LessOrEqual(t, binds, uuidBindBudget,
					"statement %d of the %s shape bound %d variables", i, testCase.name, binds)
				require.Positive(t, binds)
			}
			require.LessOrEqual(t, recorder.max(), uuidBindBudget)
		})
	}
}

// TestConditionalUpdateRunsAtBindBoundaries covers UUID-A13: SQLite integration updates run
// under the 999-variable limit at the exact calculated chunk boundary and at one row beyond it
// for the owned-UUID, one-FK, and two-condition token-name shapes.
func TestConditionalUpdateRunsAtBindBoundaries(t *testing.T) {
	for _, shape := range []struct {
		name       string
		conditions int
		table      string
		column     string
		seed       func(t *testing.T, db *gorm.DB, total int)
		values     func(total int) []uuidConditionalValue
	}{
		{
			name:       "owned uuid",
			conditions: 0,
			table:      "users",
			column:     "uuid",
			seed:       func(t *testing.T, db *gorm.DB, total int) { seedUUIDBatchUsers(t, db, total) },
			values:     uuidBatchOwnedValues,
		},
		{
			name:       "one fk",
			conditions: 1,
			table:      "users",
			column:     "inviter_uuid",
			seed:       func(t *testing.T, db *gorm.DB, total int) { seedUUIDBatchUsers(t, db, total) },
			values:     uuidBatchInviterValues,
		},
		{
			name:       "token name",
			conditions: 2,
			table:      "logs",
			column:     "token_uuid",
			seed: func(t *testing.T, db *gorm.DB, total int) {
				require.NoError(t, db.Exec("INSERT INTO channels (id, type, name, models, config) VALUES (1, 1, 'primary', 'gpt-4o', '{}')").Error)
				seedUUIDBatchLogs(t, db, total)
			},
			values: uuidBatchTokenNameValues,
		},
	} {
		shape := shape
		t.Run(shape.name, func(t *testing.T) {
			chunk := uuidChunkSize(uuidUpdateRowLimit, uuidConditionalBindsPerRow(shape.conditions), 0)
			for _, total := range []int{chunk, chunk + 1} {
				total := total
				t.Run(strconv.Itoa(total), func(t *testing.T) {
					db, _ := newUnifiedTestTopology(t)
					shape.seed(t, db, total)

					recorder := installUUIDBatchUpdateBindRecorder(t, db)
					updated, err := applyConditionalStringColumnRows(context.Background(), db, shape.table, shape.column, shape.values(total))
					require.NoError(t, err, "chunking must keep every statement under the sqlite variable cap")
					require.Equal(t, total, updated, "every driven row must be written exactly once")

					// A total of chunk+1 must split into two statements; a total of exactly
					// chunk must still fit in one.
					wantStatements := (total + chunk - 1) / chunk
					require.Len(t, recorder.observations(), wantStatements)
					for _, binds := range recorder.observations() {
						require.LessOrEqual(t, binds, uuidBindBudget)
					}

					var filled int64
					require.NoError(t, db.Table(shape.table).
						Where(shape.column+" IS NOT NULL AND "+shape.column+" != ''").
						Count(&filled).Error)
					require.EqualValues(t, total, filled)
				})
			}
		})
	}
}

// TestReferenceLookupBoundaries covers UUID-A14: distinct-reference boundaries at 0, 1, 399,
// 400, 401, and 1000 keys are deduplicated and split into query chunks of at most 400 keys.
func TestReferenceLookupBoundaries(t *testing.T) {
	const seeded = 1000
	db, _ := newUnifiedTestTopology(t)
	seedUUIDBatchUsersWithUUID(t, db, seeded)

	chunk := uuidChunkSize(uuidReferenceBatchSize, 1, 0)
	require.Equal(t, uuidReferenceBatchSize, chunk, "one id spends one bind, so the configured limit binds")

	recorder := installUUIDBatchQueryBindRecorder(t, db, "users")

	for _, distinct := range []int{0, 1, 399, 400, 401, 1000} {
		distinct := distinct
		t.Run(strconv.Itoa(distinct), func(t *testing.T) {
			// Duplicates and non-positive noise must collapse before any query is issued.
			ids := make([]int, 0, 2*distinct+2)
			for id := 1; id <= distinct; id++ {
				ids = append(ids, id)
			}
			for id := 1; id <= distinct; id += 3 {
				ids = append(ids, id)
			}
			ids = append(ids, 0, -1)

			recorder.reset()
			refs, err := loadIDUUIDMapForIDs(context.Background(), db, "users", ids)
			require.NoError(t, err)

			require.Len(t, refs, distinct)
			for id := 1; id <= distinct; id++ {
				require.Equal(t, uuidBatchTestUUID(id), refs[id], "reference %d must map to its own uuid", id)
			}

			observed := recorder.observations()
			require.Len(t, observed, (distinct+chunk-1)/chunk, "distinct keys must split into ceil(n/400) chunks")
			total := 0
			for i, binds := range observed {
				require.LessOrEqual(t, binds, uuidReferenceBatchSize,
					"reference query %d bound %d ids", i, binds)
				require.Positive(t, binds)
				total += binds
			}
			require.Equal(t, distinct, total, "every distinct id is bound exactly once across the chunks")
		})
	}
}

// TestUniquePositiveInts covers UUID-A14: reference ids are deduplicated, sorted, and stripped
// of non-positive values before any bounded lookup runs.
func TestUniquePositiveInts(t *testing.T) {
	require.Empty(t, uniquePositiveInts(nil))
	require.Empty(t, uniquePositiveInts([]int{}))
	require.Empty(t, uniquePositiveInts([]int{0, -1, -400}), "non-positive ids are never referenced")
	require.Equal(t, []int{7}, uniquePositiveInts([]int{7, 7, 7}))
	require.Equal(t, []int{1, 2, 3, 7}, uniquePositiveInts([]int{7, 3, 1, 3, 2, 0, -4, 7, 1}))
}

// TestUniqueTokenNameKeys covers UUID-A14: composite token references are deduplicated, sorted,
// and stripped of non-positive user ids and empty token names.
func TestUniqueTokenNameKeys(t *testing.T) {
	require.Empty(t, uniqueTokenNameKeys(nil))

	rows := []uuidLogTokenRow{
		{Id: 1, UserID: 2, TokenName: "beta"},
		{Id: 2, UserID: 2, TokenName: "alpha"},
		{Id: 3, UserID: 1, TokenName: "gamma"},
		{Id: 4, UserID: 2, TokenName: "beta"},
		{Id: 5, UserID: 0, TokenName: "zero-user"},
		{Id: 6, UserID: -3, TokenName: "negative-user"},
		{Id: 7, UserID: 1, TokenName: ""},
	}
	require.Equal(t, []uuidTokenNameKey{
		{userID: 1, name: "gamma"},
		{userID: 2, name: "alpha"},
		{userID: 2, name: "beta"},
	}, uniqueTokenNameKeys(rows), "keys are deduplicated and ordered by user id then name")
}

// TestTokenResolutionIsBoundedByBatchKeys covers UUID-A32 and UUID-A35: token resolution never
// materializes rows outside the current batch keys. Thousands of duplicate tokens sharing one
// key collapse into a single aggregate row, an empty owned UUID is not a match, and a single
// populated token resolves.
func TestTokenResolutionIsBoundedByBatchKeys(t *testing.T) {
	const duplicates = 2000
	db, _ := newUnifiedTestTopology(t)
	require.NoError(t, db.Exec("INSERT INTO users (id, uuid, username, password) VALUES (1, ?, 'root', 'password-hash')",
		uuidBatchTestUUID(1)).Error)

	// One key backed by many duplicate populated tokens.
	seedUUIDBatchTokens(t, db, 1, "dup", 1, duplicates, uuidBatchTestUUID)
	// One key backed by exactly one populated token.
	soloID := 1 + duplicates
	seedUUIDBatchTokens(t, db, 1, "solo", soloID, 1, uuidBatchTestUUID)
	// One key whose only token has never been assigned an owned UUID.
	blankID := soloID + 1
	seedUUIDBatchTokens(t, db, 1, "blank", blankID, 1, func(int) string { return "" })

	var seededTokens int64
	require.NoError(t, db.Table("tokens").Count(&seededTokens).Error)
	require.EqualValues(t, duplicates+2, seededTokens)

	t.Run("duplicate key collapses to one aggregate row", func(t *testing.T) {
		refs, ambiguous, err := resolveTokenUUIDsForKeys(context.Background(), db, []uuidTokenNameKey{{userID: 1, name: "dup"}})
		require.NoError(t, err)
		require.Empty(t, refs, "the migration never chooses among duplicate matches")
		// The lookup is a GROUP BY aggregate over the requested keys, so the database — not the
		// application — collapses the duplicates. Memory is bounded by the number of requested
		// keys, never by how many token rows match them: 2000 duplicate rows yield exactly one
		// scanned aggregate row, hence an ambiguous count of 1 rather than 2000.
		require.Equal(t, 1, ambiguous, "2000 duplicate tokens must materialize exactly one aggregate row")
	})

	t.Run("single populated token resolves", func(t *testing.T) {
		refs, ambiguous, err := resolveTokenUUIDsForKeys(context.Background(), db, []uuidTokenNameKey{{userID: 1, name: "solo"}})
		require.NoError(t, err)
		require.Zero(t, ambiguous)
		require.Len(t, refs, 1)
		require.Equal(t, uuidBatchTestUUID(soloID), refs[userTokenNameKey(1, "solo")])
	})

	t.Run("empty owned uuid is not a match", func(t *testing.T) {
		refs, ambiguous, err := resolveTokenUUIDsForKeys(context.Background(), db, []uuidTokenNameKey{{userID: 1, name: "blank"}})
		require.NoError(t, err)
		require.Zero(t, ambiguous)
		require.Empty(t, refs, "a token with an unpopulated uuid cannot resolve a reference")
	})

	t.Run("unrequested keys are never resolved", func(t *testing.T) {
		refs, ambiguous, err := resolveTokenUUIDsForKeys(context.Background(), db, []uuidTokenNameKey{
			{userID: 1, name: "blank"},
			{userID: 1, name: "dup"},
			{userID: 1, name: "solo"},
			{userID: 1, name: "absent"},
			{userID: 999, name: "solo"},
		})
		require.NoError(t, err)
		require.Equal(t, 1, ambiguous, "only the duplicate key is ambiguous")
		require.Len(t, refs, 1, "only keys in the batch may resolve")
		require.Equal(t, uuidBatchTestUUID(soloID), refs[userTokenNameKey(1, "solo")])
	})

	t.Run("no keys issues no lookup", func(t *testing.T) {
		refs, ambiguous, err := resolveTokenUUIDsForKeys(context.Background(), db, nil)
		require.NoError(t, err)
		require.Zero(t, ambiguous)
		require.Empty(t, refs)
	})
}

// TestResolveTokenUUIDsForLogRowsChunksKeys covers UUID-A14 and UUID-A35: log rows are reduced
// to deduplicated composite keys and resolved in bounded chunks that never exceed the reference
// batch size.
func TestResolveTokenUUIDsForLogRowsChunksKeys(t *testing.T) {
	const keys = 450
	db, _ := newUnifiedTestTopology(t)
	require.NoError(t, db.Exec("INSERT INTO users (id, uuid, username, password) VALUES (1, ?, 'root', 'password-hash')",
		uuidBatchTestUUID(1)).Error)
	for id := 1; id <= keys; id++ {
		seedUUIDBatchTokens(t, db, uuidBatchLogUserID, uuidBatchTokenName(id), id, 1, uuidBatchTestUUID)
	}

	// Each key is observed twice so deduplication, not the row count, bounds the lookup.
	rows := make([]uuidLogTokenRow, 0, 2*keys)
	for id := 1; id <= keys; id++ {
		rows = append(rows, uuidLogTokenRow{Id: id, UserID: uuidBatchLogUserID, TokenName: uuidBatchTokenName(id)})
		rows = append(rows, uuidLogTokenRow{Id: keys + id, UserID: uuidBatchLogUserID, TokenName: uuidBatchTokenName(id)})
	}

	refs, ambiguous, err := resolveTokenUUIDsForLogRows(context.Background(), db, rows)
	require.NoError(t, err)
	require.Zero(t, ambiguous)
	require.Len(t, refs, keys, "duplicate log references must collapse into one key each")
	for id := 1; id <= keys; id++ {
		require.Equal(t, uuidBatchTestUUID(id), refs[userTokenNameKey(uuidBatchLogUserID, uuidBatchTokenName(id))])
	}

	// Two binds per key keep the chunk at the configured reference batch size.
	chunk := uuidChunkSize(uuidReferenceBatchSize, 2, 0)
	require.Equal(t, uuidReferenceBatchSize, chunk)
	require.LessOrEqual(t, chunk*2, uuidBindBudget)
}
