package common

import (
	"context"
	"strings"
	"sync/atomic"
	"time"

	"github.com/Laisky/errors/v2"
	"github.com/Laisky/zap"
	"github.com/go-redis/redis/v8"

	"github.com/Laisky/one-api/common/config"
	"github.com/Laisky/one-api/common/logger"
)

// RDB exposes the active Redis client used throughout the application.
var RDB redis.Cmdable

var redisEnabled atomic.Bool

func init() {
	redisEnabled.Store(true)
}

// IsRedisEnabled reports whether Redis integration is currently active.
func IsRedisEnabled() bool {
	return redisEnabled.Load()
}

// SetRedisEnabled toggles the global Redis availability flag.
func SetRedisEnabled(enabled bool) {
	redisEnabled.Store(enabled)
}

// InitRedisClient creates the Redis client according to configuration and verifies connectivity.
// It disables Redis gracefully when the connection parameters are absent.
func InitRedisClient() (err error) {
	if config.RedisConnString == "" {
		SetRedisEnabled(false)
		logger.Logger.Info("REDIS_CONN_STRING not set, Redis is not enabled")
		return nil
	}
	if config.SyncFrequency == 0 {
		SetRedisEnabled(false)
		logger.Logger.Info("SYNC_FREQUENCY not set, Redis is disabled")
		return nil
	}
	redisConnString := config.RedisConnString
	if config.RedisMasterName == "" {
		logger.Logger.Info("Redis is enabled")
		opt, err := redis.ParseURL(redisConnString)
		if err != nil {
			logger.Logger.Fatal("failed to parse Redis connection string", zap.Error(err))
		}
		RDB = redis.NewClient(opt)
	} else {
		// cluster mode
		logger.Logger.Info("Redis cluster mode enabled")
		RDB = redis.NewUniversalClient(&redis.UniversalOptions{
			Addrs:      strings.Split(redisConnString, ","),
			Password:   config.RedisPassword,
			MasterName: config.RedisMasterName,
		})
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, err = RDB.Ping(ctx).Result()
	if err != nil {
		logger.Logger.Fatal("Redis ping test failed", zap.Error(err))
	}
	SetRedisEnabled(true)
	return nil
}

// ParseRedisOption parses the configured Redis connection string into redis.Options for direct client construction.
func ParseRedisOption() *redis.Options {
	opt, err := redis.ParseURL(config.RedisConnString)
	if err != nil {
		logger.Logger.Fatal("failed to parse Redis connection string", zap.Error(err))
	}
	return opt
}

// RedisSet stores the value at the provided key with the desired expiration, wrapping any Redis error.
func RedisSet(ctx context.Context, key string, value string, expiration time.Duration) error {
	if RDB == nil {
		return errors.New("redis not initialized")
	}
	err := RDB.Set(ctx, key, value, expiration).Err()
	if err != nil {
		return errors.Wrapf(err, "failed to set redis key: %s", key)
	}
	return nil
}

// RedisGet retrieves the string value associated with the key.
// It returns the value alongside any error generated by Redis.
func RedisGet(ctx context.Context, key string) (string, error) {
	if RDB == nil {
		return "", errors.New("redis not initialized")
	}
	val, err := RDB.Get(ctx, key).Result()
	if err != nil {
		return "", errors.Wrapf(err, "failed to get redis key: %s", key)
	}
	return val, nil
}

// RedisDel removes the specified key from Redis.
func RedisDel(ctx context.Context, key string) error {
	if RDB == nil {
		return errors.New("redis not initialized")
	}
	err := RDB.Del(ctx, key).Err()
	if err != nil {
		return errors.Wrapf(err, "failed to delete redis key: %s", key)
	}
	return nil
}

// RedisDecrease atomically decreases the numeric value stored at key by the provided delta.
func RedisDecrease(ctx context.Context, key string, value int64) error {
	if RDB == nil {
		return errors.New("redis not initialized")
	}
	err := RDB.DecrBy(ctx, key, value).Err()
	if err != nil {
		return errors.Wrapf(err, "failed to decrease redis key: %s by %d", key, value)
	}
	return nil
}
