package ali

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// qwenOpenModelRatios captures pricing and metadata for Alibaba's open-weight
// Qwen lineups exposed via Model Studio: Qwen 2 / 2.5 / 3 instruct, Qwen 1.5
// chat, Qwen 2 / 2.5 -Math / -Coder / -VL, the QwQ / QwQ-Plus / QVQ reasoning
// models, and the Qwen3 Next-80B preview pair.
//
// Open-weight models populate HuggingFaceID (matching the canonical card under
// https://huggingface.co/Qwen) and Quantization "bf16" reflecting the precision
// Alibaba serves on Model Studio (verified via the Hugging Face model cards on
// 2026-05-18). Context lengths follow the Hugging Face cards / Model Studio
// docs; where the upstream card and Model Studio differ, we prefer the served
// value. All RMB prices use ratio.MilliTokensRmb (project-rate 8 RMB/USD).
//
// Sources verified 2026-05-18:
//   - https://www.alibabacloud.com/help/en/model-studio/model-pricing
//   - https://help.aliyun.com/zh/model-studio/getting-started/models
//   - https://huggingface.co/Qwen
var qwenOpenModelRatios = map[string]adaptor.ModelConfig{
	// ----- Qwen 2.5 Instruct (open) -------------------------------------------
	// Aliyun pricing: 72b 4.11/12.37, 32b 2.06/6.17, 14b 1.03/3.09, 7b 0.52/1.03 CNY per 1M.
	"qwen2.5-72b-instruct": {
		Ratio:                       0.00411 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3.01, // 12.37 / 4.11
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
		Description:                 "Qwen2.5 72B Instruct: open-weight flagship instruct model with 128K context.",
	},
	"qwen2.5-32b-instruct": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             2.995, // 6.17 / 2.06
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-32B-Instruct",
		Description:                 "Qwen2.5 32B Instruct: open-weight mid-tier instruct model with 128K context.",
	},
	"qwen2.5-14b-instruct": {
		Ratio:                       0.00103 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3, // 3.09 / 1.03
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-14B-Instruct",
		Description:                 "Qwen2.5 14B Instruct: open-weight instruct model with 128K context.",
	},
	"qwen2.5-7b-instruct": {
		Ratio:                       0.00052 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1.98, // 1.03 / 0.52
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
		Description:                 "Qwen2.5 7B Instruct: open-weight cost-efficient instruct model with 128K context.",
	},
	"qwen2.5-3b-instruct": {
		Ratio:                       0.0006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-3B-Instruct",
		Description:                 "Qwen2.5 3B Instruct: open-weight small instruct model.",
	},
	"qwen2.5-1.5b-instruct": {
		Ratio:                       0, // limited-time free per Aliyun pricing (May 2026).
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-1.5B-Instruct",
		Description:                 "Qwen2.5 1.5B Instruct: open-weight compact instruct model (limited-time free trial).",
	},
	"qwen2.5-0.5b-instruct": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-0.5B-Instruct",
		Description:                 "Qwen2.5 0.5B Instruct: open-weight micro instruct model (free trial).",
	},

	// ----- Qwen 3 Instruct (open) ----------------------------------------------
	// Tiered between thinking / non-thinking modes; we record non-thinking base.
	// 235b 2.06/8.24, 32b 2.06/8.24, 30b-a3b 0.78/3.09, 14b 1.03/4.11,
	// 8b 0.52/2.06, 4b 0.31/1.24, 1.7b 0.31/1.24, 0.6b 0.31/1.24 CNY per 1M.
	"qwen3-235b-a22b": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 8.24 / 2.06
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Description:                 "Qwen3 235B A22B: open-weight MoE flagship (22B active) with thinking/non-thinking modes.",
	},
	"qwen3-235b-a22b-instruct-2507": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Description:                 "Qwen3 235B A22B Instruct (2507 snapshot): non-thinking instruct variant.",
	},
	"qwen3-235b-a22b-thinking-2507": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
		Description:                 "Qwen3 235B A22B Thinking (2507): open-weight reasoning flagship with chain-of-thought.",
	},
	"qwen3-32b": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4,
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-32B",
		Description:                 "Qwen3 32B: dense open-weight model with hybrid thinking/non-thinking modes.",
	},
	"qwen3-30b-a3b": {
		Ratio:                       0.00075 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 3.0 / 0.75
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
		Description:                 "Qwen3 30B A3B: open-weight MoE (3B active) with hybrid thinking modes.",
	},
	// 2507 snapshots: distinct official rows (中国内地, verified 2026-06-27).
	//   instruct (仅非思考): 0.75 / 3   thinking (仅思考): 0.75 / 7.5
	"qwen3-30b-a3b-instruct-2507": {
		Ratio:                       0.00075 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 3.0 / 0.75
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Instruct-2507",
		Description:                 "Qwen3 30B A3B Instruct (2507 snapshot): open-weight MoE (3B active), non-thinking instruct variant.",
	},
	"qwen3-30b-a3b-thinking-2507": {
		Ratio:                       0.00075 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             10, // 7.5 / 0.75 (thinking output)
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Thinking-2507",
		Description:                 "Qwen3 30B A3B Thinking (2507 snapshot): open-weight MoE reasoning variant.",
	},
	"qwen3-14b": {
		Ratio:                       0.00103 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3.99, // 4.11 / 1.03
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-14B",
		Description:                 "Qwen3 14B: dense open-weight model with hybrid thinking modes.",
	},
	"qwen3-8b": {
		Ratio:                       0.00052 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3.96, // 2.06 / 0.52
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-8B",
		Description:                 "Qwen3 8B: open-weight model with hybrid thinking modes.",
	},
	"qwen3-4b": {
		Ratio:                       0.00031 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 1.24 / 0.31
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-4B",
		Description:                 "Qwen3 4B: open-weight compact model with hybrid thinking modes.",
	},
	"qwen3-1.7b": {
		Ratio:                       0.00031 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4,
		ContextLength:               32768,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-1.7B",
		Description:                 "Qwen3 1.7B: open-weight micro model with hybrid thinking modes.",
	},
	"qwen3-0.6b": {
		Ratio:                       0.00031 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4,
		ContextLength:               32768,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-0.6B",
		Description:                 "Qwen3 0.6B: open-weight micro model with hybrid thinking modes.",
	},

	// ----- Qwen3 Next (open, preview pair) ------------------------------------
	// qwen3-next-80b-a3b series are open-weight MoE with extended thinking on
	// the -thinking variant. Pricing is treated identically to Qwen3 30b-a3b
	// (Aliyun lists them under the same tier table).
	"qwen3-next-80b-a3b-instruct": {
		Ratio:                       0.00078 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3.96,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
		Description:                 "Qwen3 Next 80B A3B Instruct: open-weight MoE (3B active) with extended 256K context.",
	},
	"qwen3-next-80b-a3b-thinking": {
		Ratio:                       0.00078 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3.96,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
		Description:                 "Qwen3 Next 80B A3B Thinking: open-weight MoE reasoning model with 256K context.",
	},

	// ----- Qwen3 Coder (open) --------------------------------------------------
	// Aliyun pricing (verified 2026-05-19, Beijing CNY/1M, 0-32K base tier):
	//   480B-A35B Instruct: 6 / 24
	//   30B-A3B Instruct:   1.5 / 6
	//   qwen3-coder-next:   1 / 4 (256K-context cost-optimized successor)
	"qwen3-coder-480b-a35b-instruct": {
		Ratio:                       0.006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 24 / 6
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		Description:                 "Qwen3-Coder 480B A35B Instruct: open-weight MoE coder flagship (0-32K base tier billed here).",
	},
	"qwen3-coder-30b-a3b-instruct": {
		Ratio:                       0.0015 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 6 / 1.5
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
		Description:                 "Qwen3-Coder 30B A3B Instruct: open-weight MoE coder (0-32K base tier billed here).",
	},
	"qwen3-coder-next": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 4 / 1
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Coder-Next",
		Description:                 "Qwen3-Coder Next: open-weight cost-optimized coder successor (256K context, 0-32K base tier billed here).",
	},

	// ----- Qwen 2 Instruct (open) ---------------------------------------------
	"qwen2-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-72B-Instruct",
		Description:                 "Qwen2 72B Instruct: previous-generation open-weight flagship.",
	},
	"qwen2-57b-a14b-instruct": {
		Ratio:                       0.0035 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               65536,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-57B-A14B-Instruct",
		Description:                 "Qwen2 57B-A14B Instruct: open-weight MoE instruct model (14B active).",
	},
	"qwen2-7b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-7B-Instruct",
		Description:                 "Qwen2 7B Instruct: open-weight previous-generation instruct model.",
	},
	"qwen2-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-1.5B-Instruct",
		Description:                 "Qwen2 1.5B Instruct: open-weight compact instruct model.",
	},
	"qwen2-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-0.5B-Instruct",
		Description:                 "Qwen2 0.5B Instruct: open-weight micro instruct model.",
	},

	// ----- Qwen 1.5 Chat (open) ------------------------------------------------
	"qwen1.5-110b-chat": {
		Ratio:                       0.008 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-110B-Chat",
		Description:                 "Qwen1.5 110B Chat: open-weight legacy flagship chat model.",
	},
	"qwen1.5-72b-chat": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-72B-Chat",
		Description:                 "Qwen1.5 72B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-32b-chat": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-32B-Chat",
		Description:                 "Qwen1.5 32B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-14b-chat": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-14B-Chat",
		Description:                 "Qwen1.5 14B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-7b-chat": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-7B-Chat",
		Description:                 "Qwen1.5 7B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-1.8b-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-1.8B-Chat",
		Description:                 "Qwen1.5 1.8B Chat: open-weight legacy compact chat model.",
	},
	"qwen1.5-0.5b-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-0.5B-Chat",
		Description:                 "Qwen1.5 0.5B Chat: open-weight legacy micro chat model.",
	},

	// ----- Qwen 2.5 / 2 Math (open) -------------------------------------------
	"qwen2.5-math-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-72B-Instruct",
		Description:                 "Qwen2.5-Math 72B Instruct: open-weight math-specialized model.",
	},
	"qwen2.5-math-7b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-7B-Instruct",
		Description:                 "Qwen2.5-Math 7B Instruct: open-weight math-specialized model.",
	},
	"qwen2.5-math-1.5b-instruct": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-1.5B-Instruct",
		Description:                 "Qwen2.5-Math 1.5B Instruct: open-weight compact math model (free trial).",
	},
	"qwen2-math-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-72B-Instruct",
		Description:                 "Qwen2-Math 72B Instruct: open-weight math-specialized model.",
	},
	"qwen2-math-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-7B-Instruct",
		Description:                 "Qwen2-Math 7B Instruct: open-weight math-specialized model.",
	},
	"qwen2-math-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-1.5B-Instruct",
		Description:                 "Qwen2-Math 1.5B Instruct: open-weight compact math model.",
	},

	// ----- Qwen 2.5 Coder (open) ----------------------------------------------
	"qwen2.5-coder-32b-instruct": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
		Description:                 "Qwen2.5-Coder 32B Instruct: open-weight coder flagship with 128K context.",
	},
	"qwen2.5-coder-14b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-14B-Instruct",
		Description:                 "Qwen2.5-Coder 14B Instruct: open-weight coder model with 128K context.",
	},
	"qwen2.5-coder-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-7B-Instruct",
		Description:                 "Qwen2.5-Coder 7B Instruct: open-weight coder model with 128K context.",
	},
	"qwen2.5-coder-3b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-3B-Instruct",
		Description:                 "Qwen2.5-Coder 3B Instruct: open-weight compact coder model.",
	},
	"qwen2.5-coder-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-1.5B-Instruct",
		Description:                 "Qwen2.5-Coder 1.5B Instruct: open-weight compact coder model.",
	},
	"qwen2.5-coder-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-0.5B-Instruct",
		Description:                 "Qwen2.5-Coder 0.5B Instruct: open-weight micro coder model.",
	},

	// ----- Qwen 2.5 VL (open vision) ------------------------------------------
	"qwen2.5-vl-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
		Description:                 "Qwen2.5-VL 72B Instruct: open-weight flagship vision-language model.",
	},
	"qwen2.5-vl-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-7B-Instruct",
		Description:                 "Qwen2.5-VL 7B Instruct: open-weight vision-language model with 128K context.",
	},
	"qwen2.5-vl-3b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-3B-Instruct",
		Description:                 "Qwen2.5-VL 3B Instruct: open-weight compact vision-language model.",
	},
	"qwen2.5-vl-2b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		// Note: Qwen2.5-VL-2B is the Hugging Face slug; left in place for callers that
		// rely on HF mapping.
		HuggingFaceID: "Qwen/Qwen2.5-VL-2B-Instruct",
		Description:   "Qwen2.5-VL 2B Instruct: open-weight compact vision-language model.",
	},
	"qwen2.5-vl-1b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		// Hugging Face card not published for the 1B variant; left blank rather
		// than guessing a slug. Operators relying on HF-id mapping should fall
		// back to the closest 2B/3B sibling.
		Description: "Qwen2.5-VL 1B Instruct: open-weight micro vision-language model (HF card not published).",
	},
	"qwen2.5-vl-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		// HF slug not published for the 0.5B variant on the Qwen org page.
		Description: "Qwen2.5-VL 0.5B Instruct: open-weight micro vision-language model (HF card not published).",
	},

	// ----- Qwen 3 VL (open vision) --------------------------------------------
	// Aliyun pricing (verified 2026-05-19, Beijing CNY/1M):
	//   235B-A22B Instruct: 2 / 8;   235B-A22B Thinking: 2 / 20
	//    32B Instruct:      2 / 8;    32B Thinking:      2 / 20
	//    30B-A3B Instruct:  0.75 / 3; 30B-A3B Thinking:  0.75 / 7.5
	//     8B Instruct:      0.5  / 2;  8B Thinking:      0.5  / 5
	// All variants are open-weight under https://huggingface.co/Qwen and serve
	// at bf16 on Model Studio.
	"qwen3-vl-235b-a22b-instruct": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 8 / 2
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
		Description:                 "Qwen3-VL 235B A22B Instruct: open-weight multimodal MoE flagship (22B active, 256K context).",
	},
	"qwen3-vl-235b-a22b-thinking": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             10, // 20 / 2
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
		Description:                 "Qwen3-VL 235B A22B Thinking: open-weight multimodal reasoning MoE flagship (22B active).",
	},
	"qwen3-vl-32b-instruct": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 8 / 2
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-32B-Instruct",
		Description:                 "Qwen3-VL 32B Instruct: open-weight dense multimodal model.",
	},
	"qwen3-vl-32b-thinking": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             10, // 20 / 2
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-32B-Thinking",
		Description:                 "Qwen3-VL 32B Thinking: open-weight dense multimodal reasoning model.",
	},
	"qwen3-vl-30b-a3b-instruct": {
		Ratio:                       0.00075 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 3 / 0.75
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
		Description:                 "Qwen3-VL 30B A3B Instruct: open-weight multimodal MoE (3B active).",
	},
	"qwen3-vl-30b-a3b-thinking": {
		Ratio:                       0.00075 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             10, // 7.5 / 0.75
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
		Description:                 "Qwen3-VL 30B A3B Thinking: open-weight multimodal MoE reasoning model (3B active).",
	},
	"qwen3-vl-8b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 2 / 0.5
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
		Description:                 "Qwen3-VL 8B Instruct: open-weight compact multimodal model.",
	},
	"qwen3-vl-8b-thinking": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             10, // 5 / 0.5
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-8B-Thinking",
		Description:                 "Qwen3-VL 8B Thinking: open-weight compact multimodal reasoning model.",
	},

	// ----- Qwen 2 VL (open vision) --------------------------------------------
	"qwen2-vl-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-VL-7B-Instruct",
		Description:                 "Qwen2-VL 7B Instruct: open-weight previous-generation vision-language model.",
	},
	"qwen2-vl-2b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-VL-2B-Instruct",
		Description:                 "Qwen2-VL 2B Instruct: open-weight compact previous-generation vision-language model.",
	},

	// ----- Qwen Audio (open) ---------------------------------------------------
	"qwen2-audio-instruct": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Audio-7B-Instruct",
		Description:                 "Qwen2-Audio Instruct: open-weight audio-understanding model (currently free trial).",
	},

	// ----- QwQ / QVQ reasoning models (open) ----------------------------------
	// Aliyun pricing: qwq-32b-preview 2.06/6.17 CNY/1M; qwq-plus 1.6/4 CNY/1M;
	// qvq-72b-preview 12.37/37.11 CNY/1M; qvq-max 8.24/32.96 CNY/1M; qvq-plus 2/5 CNY/1M.
	"qwq-32b-preview": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             2.995, // 6.17 / 2.06
		ContextLength:               32768,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QwQ-32B-Preview",
		Description:                 "QwQ 32B Preview: open-weight reasoning-focused preview model with chain-of-thought.",
	},
	"qwq-32b": {
		Ratio:                       0.00206 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             2.995,
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QwQ-32B",
		Description:                 "QwQ 32B: open-weight reasoning model with 128K context.",
	},
	"qwq-plus": {
		Ratio:                       0.0016 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             2.5, // 4 / 1.6
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QwQ-32B",
		Description:                 "QwQ Plus: managed reasoning tier (served from QwQ family) with 128K context.",
	},
	"qvq-72b-preview": {
		Ratio:                       0.01237 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             3, // 37.11 / 12.37
		ContextLength:               32768,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QVQ-72B-Preview",
		Description:                 "QVQ 72B Preview: open-weight multimodal reasoning preview model.",
	},
	"qvq-max": {
		Ratio:                       0.00824 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             4, // 32.96 / 8.24
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QVQ-72B-Preview",
		Description:                 "QVQ Max: managed multimodal reasoning tier with 128K context.",
	},
	"qvq-plus": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             2.5, // 5 / 2
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		MaxReasoningTokens:          38912,
		Description:                 "QVQ Plus: managed multimodal reasoning tier with 128K context.",
	},

	// ----- Qwen 3.5 / 3.6 medium open-weight family ---------------------------
	// Aliyun China-mainland CNY/1M (verified 2026-06-27 against
	// help.aliyun.com/zh/model-studio/model-pricing). Base tier billed here:
	//   qwen3.5-397b-a17b: 0-128K 1.2 / 7.2   (128K-256K 3 / 18)
	//   qwen3.5-122b-a10b: 0-128K 0.8 / 6.4   (128K-256K 2 / 16)
	//   qwen3.5-35b-a3b:   0-128K 0.4 / 3.2   (128K-256K 1.6 / 12.8)
	//   qwen3.5-27b:       0-128K 0.6 / 4.8   (128K-256K 1.8 / 14.4)
	//   qwen3.6-35b-a3b:   0-256K 1.8 / 10.8
	//   qwen3.6-27b:       0-256K 3 / 18
	"qwen3.5-397b-a17b": {
		Ratio:                       0.0012 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             6, // 7.2 / 1.2
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
		Description:                 "Qwen3.5 397B-A17B: open-weight multimodal hybrid-reasoning MoE flagship (17B active, 256K context; 0-128K base tier billed here).",
	},
	"qwen3.5-122b-a10b": {
		Ratio:                       0.0008 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             8, // 6.4 / 0.8
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
		Description:                 "Qwen3.5 122B-A10B: open-weight multimodal hybrid-reasoning MoE (10B active, 256K context; 0-128K base tier billed here).",
	},
	"qwen3.5-35b-a3b": {
		Ratio:                       0.0004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             8, // 3.2 / 0.4
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
		Description:                 "Qwen3.5 35B-A3B: open-weight multimodal hybrid-reasoning MoE (3B active, 256K context; 0-128K base tier billed here).",
	},
	"qwen3.5-27b": {
		Ratio:                       0.0006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             8, // 4.8 / 0.6
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-27B",
		Description:                 "Qwen3.5 27B: open-weight dense multimodal hybrid-reasoning model (256K context; 0-128K base tier billed here).",
	},
	"qwen3.6-35b-a3b": {
		Ratio:                       0.0018 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             6, // 10.8 / 1.8
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
		Description:                 "Qwen3.6 35B-A3B: open-weight MoE (3B active, 256K context; 0-256K base tier billed here).",
	},
	"qwen3.6-27b": {
		Ratio:                       0.003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             6, // 18 / 3
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.6-27B",
		Description:                 "Qwen3.6 27B: open-weight dense coding-focused model (256K context; 0-256K base tier billed here).",
	},
}
