package openai

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// gpt4oModelRatios captures pricing and metadata for the GPT-4o family
// (multimodal text-and-vision flagship and audio variants).
// Sources: https://platform.openai.com/docs/models/gpt-4o,
// https://platform.openai.com/docs/models/gpt-4o-mini,
// https://platform.openai.com/docs/models/gpt-4o-audio-preview.
var gpt4oModelRatios = map[string]adaptor.ModelConfig{
	"gpt-4o": {
		Ratio:                       2.5 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            1.25 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o: multimodal flagship model with text and vision input, 128K context.",
	},
	"gpt-4o-2024-05-13": {
		Ratio:                       5.0 * ratio.MilliTokensUsd,
		CompletionRatio:             3.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o snapshot from 2024-05-13 (initial release).",
	},
	"gpt-4o-2024-08-06": {
		Ratio:                       2.5 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            1.25 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o snapshot from 2024-08-06 with structured outputs.",
	},
	"gpt-4o-2024-11-20": {
		Ratio:                       2.5 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            1.25 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o snapshot from 2024-11-20.",
	},
	"gpt-4o-mini": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.075 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o mini: cost-efficient multimodal small model, 128K context.",
	},
	"gpt-4o-mini-2024-07-18": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.075 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o mini snapshot from 2024-07-18.",
	},
	"gpt-4o-mini-audio-preview": {
		Ratio:           0.15 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           10.0 / 0.15,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o mini audio preview: speech in/out via dedicated audio endpoint. (RETIRED 2026-05-07; use gpt-audio-mini)",
	},
	"gpt-4o-mini-audio-preview-2024-12-17": {
		Ratio:           0.15 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           10.0 / 0.15,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o mini audio preview snapshot from 2024-12-17. (RETIRED 2026-05-07; use gpt-audio-mini)",
	},
	"gpt-4o-audio-preview": {
		Ratio:           2.5 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           16,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o audio preview: speech in/out via dedicated audio endpoint. (RETIRED 2026-05-07; use gpt-audio-1.5)",
	},
	"gpt-4o-audio-preview-2024-12-17": {
		Ratio:           2.5 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           16,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o audio preview snapshot from 2024-12-17. (RETIRED 2026-05-07; use gpt-audio-1.5)",
	},
	"gpt-4o-audio-preview-2024-10-01": {
		Ratio:           2.5 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           40,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o audio preview snapshot from 2024-10-01. (RETIRED 2026-05-07; use gpt-audio-1.5)",
	},
	"gpt-4o-audio-preview-2025-06-03": {
		Ratio:           2.5 * ratio.MilliTokensUsd,
		CompletionRatio: 4.0,
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio:           16,
			CompletionRatio:       2,
			PromptTokensPerSecond: 10,
		},
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4o audio preview snapshot from 2025-06-03. (RETIRED 2026-05-07; use gpt-audio-1.5)",
	},
	// chatgpt-4o-latest: rolling alias mirroring the consumer ChatGPT default model.
	// Retired from OpenAI API on 2026-02-17 (replaced by chat-latest). Kept here for
	// backward compatibility with channels that still proxy this name; new traffic
	// should use chat-latest (registered separately under the GPT-5 family pricing).
	// Source: https://developers.openai.com/api/docs/deprecations
	"chatgpt-4o-latest": {
		Ratio:                       5.0 * ratio.MilliTokensUsd,
		CompletionRatio:             15.0 / 5.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             16384,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "ChatGPT-4o latest: legacy alias (retired from OpenAI API 2026-02-17). Use chat-latest instead.",
	},
}
