package openai

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// oSeriesModelRatios captures pricing and metadata for OpenAI's o-series reasoning
// models (o1, o3, o4-mini lines plus deep-research variants). These are reasoning
// models: SupportedSamplingParameters is restricted to ["seed","max_tokens"].
//
// Sources verified 2026-05-01:
//   - https://platform.openai.com/docs/models/o1 (o1: 200K/100K)
//   - https://platform.openai.com/docs/models/o3 (o3: 200K/100K)
//   - https://platform.openai.com/docs/models/o4-mini (o4-mini: 200K/100K)
var oSeriesReasoningFeatures = []string{"reasoning", "tools"}

// oSeriesMediumOnlyEfforts is the constrained reasoning_effort set OpenAI exposes
// for o1/o3/o4 chat models. The Responses/Chat APIs reject other levels for these
// models; the relay clamps to "medium" before dispatch.
var oSeriesMediumOnlyEfforts = []string{"medium"}

var oSeriesModelRatios = map[string]adaptor.ModelConfig{
	// o1 family
	"o1": {
		Ratio:                       15.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            7.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1: reasoning model with 200K context and 100K output budget. (retires 2026-10-23; migrate to gpt-5.5)",
	},
	"o1-2024-12-17": {
		Ratio:                       15.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            7.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 snapshot from 2024-12-17. (retires 2026-10-23; migrate to gpt-5.5)",
	},
	"o1-pro": {
		Ratio:                       150.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 Pro: extended-reasoning premium tier of o1. (retires 2026-10-23; migrate to gpt-5.5-pro)",
	},
	"o1-pro-2025-03-19": {
		Ratio:                       150.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 Pro snapshot from 2025-03-19. (retires 2026-10-23; migrate to gpt-5.5-pro)",
	},
	"o1-preview": {
		Ratio:                       15.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            7.5 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 preview: original o1 research preview (text-only).",
	},
	"o1-preview-2024-09-12": {
		Ratio:                       15.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            7.5 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             32768,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 preview snapshot from 2024-09-12.",
	},
	"o1-mini": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.55 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 mini: cost-efficient reasoning model (text-only).",
	},
	"o1-mini-2024-09-12": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.55 * ratio.MilliTokensUsd,
		ContextLength:               128000,
		MaxOutputTokens:             65536,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           oSeriesReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o1 mini snapshot from 2024-09-12.",
	},
	// o3 family
	"o3": {
		Ratio:                       2.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3: advanced reasoning model with 200K context.",
	},
	"o3-2025-04-16": {
		Ratio:                       2.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3 snapshot from 2025-04-16. (retires 2026-12-11; migrate to gpt-5.5)",
	},
	"o3-mini": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.55 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3 mini: cost-efficient reasoning successor to o1-mini. (API retirement 2026-10-23; use gpt-5.5)",
	},
	"o3-mini-2025-01-31": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.55 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3 mini snapshot from 2025-01-31.",
	},
	"o3-pro": {
		Ratio:                       20.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3-pro: o3 with extra compute for highest-quality responses; Responses API only (may take minutes per completion). Snapshot: o3-pro-2025-06-10.",
	},
	"o3-pro-2025-06-10": {
		Ratio:                       20.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3-pro snapshot 2025-06-10. (retires 2026-12-11; migrate to gpt-5.5-pro)",
	},
	"o3-deep-research": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            2.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3 deep research: agentic research model with built-in browsing.",
	},
	"o3-deep-research-2025-06-26": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            2.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o3 deep research snapshot from 2025-06-26 (deprecated per OpenAI docs).",
	},
	// o4 family
	"o4-mini": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.275 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o4 mini: fast reasoning model with 200K context. (API retirement 2026-10-23; use gpt-5.4-mini)",
	},
	"o4-mini-2025-04-16": {
		Ratio:                       1.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.275 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"structured_outputs"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o4 mini snapshot from 2025-04-16.",
	},
	"o4-mini-deep-research": {
		Ratio:                       2.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o4 mini deep research: cost-efficient agentic research model.",
	},
	"o4-mini-deep-research-2025-06-26": {
		Ratio:                       2.0 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             100000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, oSeriesReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		SupportedReasoningEfforts:   oSeriesMediumOnlyEfforts,
		DefaultReasoningEffort:      "medium",
		Description:                 "o4 mini deep research snapshot from 2025-06-26.",
	},
}
