package openai

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// gpt4ModelRatios captures pricing and metadata for legacy GPT-4 family chat models.
// Sources: https://platform.openai.com/docs/models/gpt-4 and
// https://platform.openai.com/docs/models/gpt-4-turbo.
var gpt4ModelRatios = map[string]adaptor.ModelConfig{
	"gpt-4": {
		Ratio:                       30.0 * ratio.MilliTokensUsd,
		CompletionRatio:             60.0 / 30.0,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4: original 8K-context flagship model (legacy).",
	},
	"gpt-4-0314": {
		Ratio:                       30.0 * ratio.MilliTokensUsd,
		CompletionRatio:             60.0 / 30.0,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 snapshot from 2023-03-14.",
	},
	"gpt-4-0613": {
		Ratio:                       30.0 * ratio.MilliTokensUsd,
		CompletionRatio:             60.0 / 30.0,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 snapshot from 2023-06-13 with function calling.",
	},
	"gpt-4-32k": {
		Ratio:                       60.0 * ratio.MilliTokensUsd,
		CompletionRatio:             120.0 / 60.0,
		ContextLength:               32768,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 with 32K context window (legacy).",
	},
	"gpt-4-32k-0314": {
		Ratio:                       60.0 * ratio.MilliTokensUsd,
		CompletionRatio:             120.0 / 60.0,
		ContextLength:               32768,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 32K snapshot from 2023-03-14.",
	},
	"gpt-4-32k-0613": {
		Ratio:                       60.0 * ratio.MilliTokensUsd,
		CompletionRatio:             120.0 / 60.0,
		ContextLength:               32768,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 32K snapshot from 2023-06-13.",
	},
	"gpt-4-1106-preview": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo preview snapshot from 2023-11-06 with 128K context.",
	},
	"gpt-4-0125-preview": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo preview snapshot from 2024-01-25.",
	},
	"gpt-4-turbo-preview": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo preview alias (text-only).",
	},
	"gpt-4-vision-preview": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo with Vision preview (image-input legacy).",
	},
	"gpt-4-turbo": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo with Vision: 128K context, image input.",
	},
	"gpt-4-turbo-2024-04-09": {
		Ratio:                       10.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 10.0,
		ContextLength:               128000,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools", "json_mode"},
		SupportedSamplingParameters: standardSamplingParameters(),
		Description:                 "GPT-4 Turbo snapshot from 2024-04-09 with vision.",
	},
}
