package siliconflow

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// Reusable metadata fragments for SiliconFlow-served open-weight models. SiliconFlow
// re-hosts upstream HuggingFace builds and exposes them through an OpenAI-compatible
// chat completion API. Most models are served at BF16 unless the upstream card
// explicitly specifies a quantized variant.
//
// Sources:
//   - https://docs.siliconflow.cn/cn/userguide/capabilities/text-generation
//   - https://siliconflow.cn/zh-cn/models
//   - Per-model HuggingFace cards (linked via HuggingFaceID).
var (
	// siliconflowTextModalities advertises the text-only modality used by every
	// chat model currently enumerated in this adaptor.
	siliconflowTextModalities = []string{"text"}

	// siliconflowChatSamplingParams enumerates the OpenAI-compatible sampling
	// parameters SiliconFlow's /v1/chat/completions accepts. Per the upstream
	// guide, callers can additionally pass top_k and frequency_penalty alongside
	// the standard OAI knobs.
	siliconflowChatSamplingParams = []string{
		"temperature",
		"top_p",
		"top_k",
		"max_tokens",
		"stop",
		"presence_penalty",
		"frequency_penalty",
		"seed",
		"response_format",
		"tools",
		"tool_choice",
	}

	// siliconflowLegacySamplingParams is the conservative parameter set advertised
	// for older small models (Qwen2 0.5B/1.5B, ChatGLM3, Yi 1.5 6B, Mistral v0.2)
	// that predate widespread tool/JSON support on SiliconFlow's bridge.
	siliconflowLegacySamplingParams = []string{
		"temperature",
		"top_p",
		"top_k",
		"max_tokens",
		"stop",
		"frequency_penalty",
	}

	// siliconflowChatFeatures lists the tool/JSON capabilities advertised by
	// SiliconFlow chat models that support function calling per the upstream docs.
	siliconflowChatFeatures = []string{"tools", "json_mode"}
)

// ModelRatios contains a conservative SiliconFlow compatibility snapshot.
// Model list is derived from the keys of this map, eliminating redundancy.
// SiliconFlow's public site is partially account-gated, so this file
// intentionally avoids speculative churn and only enumerates models with
// publicly visible USD pricing on the English pricing page.
//
// Pricing sources (retrieved 2026-06-13):
//   - https://www.siliconflow.com/pricing (English; USD per million tokens / image / second)
//   - https://siliconflow.cn/pricing (Chinese; CNY per million tokens — converted at 0.14 USD/CNY for legacy aliases)
//   - https://siliconflow.cn/zh-cn/models (catalog, partially login-gated)
//
// Capability metadata is derived from upstream HuggingFace model cards plus the
// SiliconFlow text-generation guide.
var ModelRatios = map[string]adaptor.ModelConfig{
	// SiliconFlow Models - Based on https://siliconflow.cn/pricing
	"deepseek-chat": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               65536,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V2.5",
		Description:                 "SiliconFlow legacy alias for DeepSeek V2.5 chat (fp8, 64K context).",
	},
	"deepseek-coder": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               65536,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-Coder-V2-Instruct",
		Description:                 "SiliconFlow legacy alias for DeepSeek Coder V2 instruct (fp8, 64K context).",
	},
	"Qwen/Qwen2-72B-Instruct": {
		Ratio:                       0.56 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-72B-Instruct",
		Description:                 "Alibaba Qwen2 72B Instruct dense chat model with 128K context and tool/JSON support.",
	},
	"Qwen/Qwen2-7B-Instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-7B-Instruct",
		Description:                 "Alibaba Qwen2 7B Instruct chat model with 128K context.",
	},
	"Qwen/Qwen2-1.5B-Instruct": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-1.5B-Instruct",
		Description:                 "Alibaba Qwen2 1.5B Instruct compact chat model with 32K context.",
	},
	"Qwen/Qwen2-0.5B-Instruct": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-0.5B-Instruct",
		Description:                 "Alibaba Qwen2 0.5B Instruct ultra-compact chat model with 32K context.",
	},
	"meta-llama/Meta-Llama-3-8B-Instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "meta-llama/Meta-Llama-3-8B-Instruct",
		Description:                 "Meta Llama 3 8B Instruct chat model with 8K context.",
	},
	"meta-llama/Meta-Llama-3-70B-Instruct": {
		Ratio:                       0.56 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "meta-llama/Meta-Llama-3-70B-Instruct",
		Description:                 "Meta Llama 3 70B Instruct dense chat model with 8K context.",
	},
	"meta-llama/Meta-Llama-3.1-8B-Instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "meta-llama/Meta-Llama-3.1-8B-Instruct",
		Description:                 "Meta Llama 3.1 8B Instruct chat model with 128K context and tool support.",
	},
	"meta-llama/Meta-Llama-3.1-70B-Instruct": {
		Ratio:                       0.56 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "meta-llama/Meta-Llama-3.1-70B-Instruct",
		Description:                 "Meta Llama 3.1 70B Instruct dense chat model with 128K context and tool support.",
	},
	"meta-llama/Meta-Llama-3.1-405B-Instruct": {
		Ratio:                       2.8 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "meta-llama/Meta-Llama-3.1-405B-Instruct",
		Description:                 "Meta Llama 3.1 405B Instruct flagship dense chat model with 128K context; served at fp8 by SiliconFlow.",
	},
	"mistralai/Mistral-7B-Instruct-v0.2": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "mistralai/Mistral-7B-Instruct-v0.2",
		Description:                 "Mistral 7B Instruct v0.2 chat model with 32K context (legacy build, no native tool calling).",
	},
	"mistralai/Mixtral-8x7B-Instruct-v0.1": {
		Ratio:                       0.56 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "mistralai/Mixtral-8x7B-Instruct-v0.1",
		Description:                 "Mistral Mixtral 8x7B Instruct v0.1 sparse MoE chat model with 32K context.",
	},
	"01-ai/Yi-1.5-9B-Chat-16K": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               16384,
		MaxOutputTokens:             4096,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "01-ai/Yi-1.5-9B-Chat-16K",
		Description:                 "01.AI Yi 1.5 9B chat model with 16K context (long-context variant).",
	},
	"01-ai/Yi-1.5-6B-Chat": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             4096,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "01-ai/Yi-1.5-6B-Chat",
		Description:                 "01.AI Yi 1.5 6B chat model with 4K context.",
	},
	"THUDM/glm-4-9b-chat": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "THUDM/glm-4-9b-chat",
		Description:                 "Zhipu THUDM GLM-4 9B chat model with 128K context and native tool calling.",
	},
	"THUDM/chatglm3-6b": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             4096,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowLegacySamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "THUDM/chatglm3-6b",
		Description:                 "Zhipu THUDM ChatGLM3 6B legacy chat model with 8K context.",
	},
	"internlm/internlm2_5-7b-chat": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "internlm/internlm2_5-7b-chat",
		Description:                 "Shanghai AI Lab InternLM 2.5 7B chat model with 32K context and tool support.",
	},
	"google/gemma-2-9b-it": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "google/gemma-2-9b-it",
		Description:                 "Google Gemma 2 9B instruction-tuned chat model with 8K context.",
	},
	"google/gemma-2-27b-it": {
		Ratio:                       0.28 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "google/gemma-2-27b-it",
		Description:                 "Google Gemma 2 27B instruction-tuned chat model with 8K context.",
	},

	// === 2026-era models (USD pricing from https://www.siliconflow.com/pricing) ===

	"deepseek-ai/DeepSeek-V4-Pro": {
		// $1.6/M input, $0.135/M cached, $3.135/M output (verified 2026-06-27 against siliconflow.com/models/deepseek-v4-pro).
		// MoE: 1.6T total / 49B activated, native 1M context, MIT license.
		Ratio:                       1.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.135 / 1.6,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             393216,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
		Description:                 "DeepSeek V4 Pro flagship MoE (1.6T/49B) with 1M context and switchable Non-Think/Think High/Think Max reasoning modes on SiliconFlow.",
	},
	"deepseek-ai/DeepSeek-V4-Flash": {
		// $0.13/M input, $0.028/M cached, $0.28/M output (verified 2026-06-14 against siliconflow.com/models/deepseek-v4-flash).
		// MoE: 284B total / 13B activated, 1M context, MIT license.
		Ratio:                       0.13 * ratio.MilliTokensUsd,
		CompletionRatio:             0.28 / 0.13,
		CachedInputRatio:            0.028 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             393216,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
		Description:                 "DeepSeek V4 Flash efficiency-optimized MoE (284B/13B) with 1M context and switchable thinking modes on SiliconFlow.",
	},
	"deepseek-ai/DeepSeek-V3.2": {
		// $0.27/M input, $0.135/M cached, $0.42/M output (production-grade sparse-attention model).
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             0.42 / 0.27,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               163840,
		MaxOutputTokens:             163840,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
		Description:                 "DeepSeek V3.2 production sparse-attention MoE hybrid reasoning + chat model on SiliconFlow.",
	},
	"deepseek-ai/DeepSeek-V3.2-Exp": {
		// $0.27/M input, $0.41/M output (sparse-attention long-context experimental variant).
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             0.41 / 0.27,
		ContextLength:               163840,
		MaxOutputTokens:             163840,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
		Description:                 "DeepSeek V3.2 Exp sparse-attention hybrid reasoning + chat MoE model on SiliconFlow.",
	},
	"Qwen/Qwen3-235B-A22B-Thinking-2507": {
		// $0.35/M input, $1.42/M output thinking variant.
		Ratio:                       0.35 * ratio.MilliTokensUsd,
		CompletionRatio:             1.42 / 0.35,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
		Description:                 "Alibaba Qwen3 235B/A22B Thinking MoE reasoning model with 256K context on SiliconFlow.",
	},
	"Qwen/Qwen3-235B-A22B-Instruct-2507": {
		// SiliconFlow publishes the instruct variant alongside the thinking variant.
		// Same input price tier as the thinking model on the public board.
		Ratio:                       0.35 * ratio.MilliTokensUsd,
		CompletionRatio:             1.42 / 0.35,
		ContextLength:               262144,
		MaxOutputTokens:             16384,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Description:                 "Alibaba Qwen3 235B/A22B Instruct MoE chat model with 256K context on SiliconFlow. (RETIRED 2026-05-15)",
	},
	"moonshotai/Kimi-K2.5": {
		// $0.45/M input, $0.07/M cached, $2.25/M output (verified 2026-05-19 on https://www.siliconflow.com/models/kimi-k2-5).
		Ratio:                       0.45 * ratio.MilliTokensUsd,
		CompletionRatio:             2.25 / 0.45,
		CachedInputRatio:            0.07 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.5",
		Description:                 "Moonshot Kimi K2.5 native multimodal MoE (1T/32B) agentic model with 256K context and switchable thinking modes on SiliconFlow.",
	},
	"moonshotai/Kimi-K2.6": {
		// $0.77/M input, $0.20/M cached, $4.00/M output.
		Ratio:                       0.77 * ratio.MilliTokensUsd,
		CompletionRatio:             4.00 / 0.77,
		CachedInputRatio:            0.20 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.6",
		Description:                 "Moonshot Kimi K2.6 frontier-scale multimodal MoE agentic model with 256K context on SiliconFlow.",
	},
	"moonshotai/Kimi-K2.7-Code": {
		// $0.94/M input, $0.19/M cached, $4.00/M output. 262K context.
		Ratio:                       0.94 * ratio.MilliTokensUsd,
		CompletionRatio:             4.00 / 0.94,
		CachedInputRatio:            0.19 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
		Description:                 "Moonshot Kimi K2.7 Code coding-focused agentic MoE model with 262K context on SiliconFlow.",
	},
	"moonshotai/Kimi-K2-Instruct-0905": {
		// $0.40/M input, $2.00/M output. 262K context. Older but stable.
		Ratio:                       0.40 * ratio.MilliTokensUsd,
		CompletionRatio:             2.00 / 0.40,
		ContextLength:               262144,
		MaxOutputTokens:             16384,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
		Description:                 "Moonshot Kimi K2 Instruct (0905 refresh) long-context MoE chat model with 256K context on SiliconFlow. (RETIRED 2026-05-15)",
	},
	"moonshotai/Kimi-K2-Thinking": {
		// $0.55/M input, $2.50/M output. 262K context. Reasoning-focused open-source thinking model.
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             2.50 / 0.55,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
		Description:                 "Moonshot Kimi K2 Thinking reasoning MoE model with 262K context on SiliconFlow.",
	},
	"zai-org/GLM-4.7": {
		// $0.42/M input, $0.11/M cached, $2.20/M output. 205K context per public model page.
		Ratio:                       0.42 * ratio.MilliTokensUsd,
		CompletionRatio:             2.20 / 0.42,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             204800,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "zai-org/GLM-4.7",
		Description:                 "Zhipu GLM-4.7 chat model with native tool calling and 205K context on SiliconFlow.",
	},
	"zai-org/GLM-5": {
		// $0.95/M input, $0.20/M cached, $2.55/M output. Sparse MoE 750B/40B, 205K context.
		Ratio:                       0.95 * ratio.MilliTokensUsd,
		CompletionRatio:             2.55 / 0.95,
		CachedInputRatio:            0.20 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "zai-org/GLM-5",
		Description:                 "Zhipu GLM-5 next-gen sparse MoE (750B/40B) with DeepSeek Sparse Attention for agentic and long-horizon tasks on SiliconFlow.",
	},
	"zai-org/GLM-5.1": {
		// $1.19/M input, $0.60/M cached, $3.74/M output. 205K context.
		Ratio:                       1.19 * ratio.MilliTokensUsd,
		CompletionRatio:             3.74 / 1.19,
		CachedInputRatio:            0.6 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "zai-org/GLM-5.1",
		Description:                 "Zhipu GLM-5.1 flagship reasoning + agentic model with 205K context on SiliconFlow.",
	},
	"zai-org/GLM-5.2": {
		// $1.302/M input, $0.26/M cached, $4.092/M output. 1M-token context.
		Ratio:                       1.302 * ratio.MilliTokensUsd,
		CompletionRatio:             4.092 / 1.302,
		CachedInputRatio:            0.26 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             262144,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "zai-org/GLM-5.2",
		Description:                 "Zhipu GLM-5.2 flagship reasoning + agentic engineering model with a 1M-token context window on SiliconFlow.",
	},
	"zai-org/GLM-4.6": {
		// $0.39/M input, $1.90/M output. 205K context.
		Ratio:                       0.39 * ratio.MilliTokensUsd,
		CompletionRatio:             1.90 / 0.39,
		ContextLength:               204800,
		MaxOutputTokens:             204800,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "zai-org/GLM-4.6",
		Description:                 "Zhipu GLM-4.6 chat model with 205K context on SiliconFlow. (RETIRED 2026-05-15)",
	},

	// === Qwen3.5 / Qwen3.6 (April 2026 lineup, Apache-2.0) ===
	"Qwen/Qwen3.6-27B": {
		// $0.30/M input, $3.20/M output. Dense 27B causal vision LM, 262K context.
		Ratio:                       0.30 * ratio.MilliTokensUsd,
		CompletionRatio:             3.20 / 0.30,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.6-27B",
		Description:                 "Alibaba Qwen3.6 27B dense vision-capable chat/coding model with 262K context on SiliconFlow.",
	},
	"Qwen/Qwen3.6-35B-A3B": {
		// $0.20/M input, $1.60/M output. MoE 35B/3B active, 262K context.
		Ratio:                       0.20 * ratio.MilliTokensUsd,
		CompletionRatio:             1.60 / 0.20,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
		Description:                 "Alibaba Qwen3.6 35B/3B-active MoE vision-capable chat model with 262K context on SiliconFlow.",
	},
	"Qwen/Qwen3.5-9B": {
		// $0.10/M input, $0.15/M output. Dense 9B, 262K context.
		Ratio:                       0.10 * ratio.MilliTokensUsd,
		CompletionRatio:             0.15 / 0.10,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-9B",
		Description:                 "Alibaba Qwen3.5 9B compact chat model with 262K context on SiliconFlow.",
	},
	"Qwen/Qwen3.5-27B": {
		// $0.25/M input, $2.00/M output. Dense 27B, 262K context.
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             2.00 / 0.25,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-27B",
		Description:                 "Alibaba Qwen3.5 27B dense chat model with 262K context on SiliconFlow.",
	},
	"Qwen/Qwen3.5-122B-A10B": {
		// $0.26/M input, $2.08/M output. MoE 122B/10B active, 262K context.
		Ratio:                       0.26 * ratio.MilliTokensUsd,
		CompletionRatio:             2.08 / 0.26,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
		Description:                 "Alibaba Qwen3.5 122B/10B-active MoE chat model with 262K context on SiliconFlow.",
	},

	// === Other 2026 models ===
	"google/gemma-4-26b-a4b-it": {
		// $0.12/M input, $0.40/M output. MoE 26B/4B active, 262K context (matches Cloudflare entry).
		Ratio:                       0.12 * ratio.MilliTokensUsd,
		CompletionRatio:             0.40 / 0.12,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "google/gemma-4-26b-a4b-it",
		Description:                 "Google Gemma 4 26B/4B-active MoE multimodal chat model with 256K context on SiliconFlow.",
	},
	"google/gemma-4-31b-it": {
		// $0.13/M input, $0.40/M output. Dense 31B, 262K context.
		Ratio:                       0.13 * ratio.MilliTokensUsd,
		CompletionRatio:             0.40 / 0.13,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"tools", "reasoning"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "google/gemma-4-31b-it",
		Description:                 "Google Gemma 4 31B dense multimodal chat model with 262K context on SiliconFlow.",
	},
	"google/gemma-4-12B-it": {
		// $0.10/M input, $0.30/M output. 262K context. Native function-calling.
		Ratio:                       0.10 * ratio.MilliTokensUsd,
		CompletionRatio:             0.30 / 0.10,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "google/gemma-4-12B-it",
		Description:                 "Google Gemma 4 12B instruction-tuned chat model with 262K context and native function-calling on SiliconFlow.",
	},
	"MiniMaxAI/MiniMax-M2.5": {
		// $0.30/M input, $0.03/M cached, $1.20/M output. 197K context.
		Ratio:                       0.30 * ratio.MilliTokensUsd,
		CompletionRatio:             1.20 / 0.30,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               196608,
		MaxOutputTokens:             131072,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "MiniMaxAI/MiniMax-M2.5",
		Description:                 "MiniMax M2.5 long-context chat model with 197K context on SiliconFlow.",
	},

	"MiniMaxAI/MiniMax-M3": {
		Ratio:                       0.30 * ratio.MilliTokensUsd,
		CompletionRatio:             1.20 / 0.30,
		CachedInputRatio:            0.06 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             131072,
		InputModalities:             []string{"text", "image", "video"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		HuggingFaceID:               "MiniMaxAI/MiniMax-M3",
		Description:                 "MiniMax M3 native multimodal flagship (text+image+video input, 1M context, 131K output, $0.30/$1.20 per 1M).",
	},
	"tencent/Hy3-preview": {
		Ratio:                       0.066 * ratio.MilliTokensUsd,
		CompletionRatio:             0.26 / 0.066,
		CachedInputRatio:            0.029 * ratio.MilliTokensUsd, // $0.029/M cached (verified 2026-06-14 against siliconflow.com/models/hy3-preview)
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Description:                 "Tencent Hunyuan 3 Preview (hy3-preview) MoE flagship, 262K context, $0.066/$0.26 per 1M.",
	},
	"tencent/Hunyuan-A13B-Instruct": {
		// $0.14/M input, $0.57/M output. MoE A13B, 131K context per metadata table.
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             0.57 / 0.14,
		ContextLength:               131072,
		MaxOutputTokens:             131072,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"json_mode"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "tencent/Hunyuan-A13B-Instruct",
		Description:                 "Tencent Hunyuan A13B Instruct MoE chat model with 131K context on SiliconFlow.",
	},
	"zai-org/GLM-5V-Turbo": {
		Ratio:                       1.20 * ratio.MilliTokensUsd,
		CompletionRatio:             4.00 / 1.20,
		CachedInputRatio:            0.24 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		HuggingFaceID:               "zai-org/GLM-5V-Turbo",
		Description:                 "Zhipu GLM-5V-Turbo native multimodal vision model (205K ctx, $1.20/$4.00 per 1M).",
	},
	"zai-org/GLM-4.5-Air": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             0.86 / 0.14,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		HuggingFaceID:               "zai-org/GLM-4.5-Air",
		Description:                 "Zhipu GLM-4.5 Air reasoning model (131K ctx, $0.14/$0.86 per 1M).",
	},
	"openai/gpt-oss-120b": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             0.45 / 0.05,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"json_mode"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Description:                 "OpenAI GPT-OSS 120B reasoning MoE model hosted on SiliconFlow (131K ctx, $0.05/$0.45 per 1M).",
	},
	"openai/gpt-oss-20b": {
		Ratio:                       0.04 * ratio.MilliTokensUsd,
		CompletionRatio:             0.18 / 0.04,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           []string{"json_mode"},
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		Description:                 "OpenAI GPT-OSS 20B reasoning model hosted on SiliconFlow (131K ctx, $0.04/$0.18 per 1M).",
	},
	"deepseek-ai/DeepSeek-V3.1": {
		// $0.27/M input, $1.00/M output. 164K context. Distinct from the later V3.1-Terminus refresh.
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             1.00 / 0.27,
		ContextLength:               163840,
		MaxOutputTokens:             163840,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
		Description:                 "DeepSeek V3.1 reasoning model hosted on SiliconFlow (164K ctx, $0.27/$1.00 per 1M).",
	},
	"deepseek-ai/DeepSeek-V3.1-Terminus": {
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             1.00 / 0.27,
		ContextLength:               163840,
		MaxOutputTokens:             163840,
		InputModalities:             siliconflowTextModalities,
		OutputModalities:            siliconflowTextModalities,
		SupportedFeatures:           siliconflowChatFeatures,
		SupportedSamplingParameters: siliconflowChatSamplingParams,
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1-Terminus",
		Description:                 "DeepSeek V3.1 Terminus reasoning model hosted on SiliconFlow (164K ctx, $0.27/$1.00 per 1M).",
	},

	// === Embedding models (BAAI, free tier on siliconflow.cn; Pro/ variants are paid at CNY 0.07/M) ===
	"BAAI/bge-m3": {
		// Free tier on SiliconFlow. Non-nil Embedding marks this as an embedding model for channel testing.
		Ratio:           0,
		CompletionRatio: 1.0,
		ContextLength:   8192,
		InputModalities: siliconflowTextModalities,
		Embedding:       &adaptor.EmbeddingPricingConfig{},
		HuggingFaceID:   "BAAI/bge-m3",
		Description:     "BAAI BGE-M3 multilingual text embedding model (8K context), free tier on SiliconFlow.",
	},
	"BAAI/bge-large-zh-v1.5": {
		// Free tier on SiliconFlow.
		Ratio:           0,
		CompletionRatio: 1.0,
		ContextLength:   512,
		InputModalities: siliconflowTextModalities,
		Embedding:       &adaptor.EmbeddingPricingConfig{},
		HuggingFaceID:   "BAAI/bge-large-zh-v1.5",
		Description:     "BAAI BGE-Large Chinese v1.5 text embedding model (512 context), free tier on SiliconFlow.",
	},
	"BAAI/bge-large-en-v1.5": {
		// Free tier on SiliconFlow.
		Ratio:           0,
		CompletionRatio: 1.0,
		ContextLength:   512,
		InputModalities: siliconflowTextModalities,
		Embedding:       &adaptor.EmbeddingPricingConfig{},
		HuggingFaceID:   "BAAI/bge-large-en-v1.5",
		Description:     "BAAI BGE-Large English v1.5 text embedding model (512 context), free tier on SiliconFlow.",
	},

	// === Image models (USD per image) ===
	"black-forest-labs/FLUX.1-schnell": {
		Ratio: 0, CompletionRatio: 1.0,
		Image: &adaptor.ImagePricingConfig{
			PricePerImageUsd: 0.0014,
			MinImages:        1,
			DefaultSize:      "1024x1024",
		},
		InputModalities:  []string{"text"},
		OutputModalities: []string{"image"},
		HuggingFaceID:    "black-forest-labs/FLUX.1-schnell",
		Description:      "FLUX.1 [schnell] 12B Apache-licensed text-to-image model on SiliconFlow.",
	},
	"black-forest-labs/FLUX.1.1-pro": {
		Ratio: 0, CompletionRatio: 1.0,
		Image: &adaptor.ImagePricingConfig{
			PricePerImageUsd: 0.04,
			MinImages:        1,
			DefaultSize:      "1024x1024",
		},
		InputModalities:  []string{"text"},
		OutputModalities: []string{"image"},
		Description:      "FLUX 1.1 [pro] managed text-to-image generator on SiliconFlow.",
	},
	"black-forest-labs/FLUX.2-pro": {
		Ratio: 0, CompletionRatio: 1.0,
		Image: &adaptor.ImagePricingConfig{
			PricePerImageUsd: 0.03,
			MinImages:        1,
			DefaultSize:      "1024x1024",
		},
		InputModalities:  []string{"text", "image"},
		OutputModalities: []string{"image"},
		Description:      "FLUX.2 [pro] high-resolution text-to-image and multi-reference editing on SiliconFlow.",
	},
	"black-forest-labs/FLUX.2-flex": {
		Ratio: 0, CompletionRatio: 1.0,
		Image: &adaptor.ImagePricingConfig{
			PricePerImageUsd: 0.06,
			MinImages:        1,
			DefaultSize:      "1024x1024",
		},
		InputModalities:  []string{"text", "image"},
		OutputModalities: []string{"image"},
		Description:      "FLUX.2 [flex] tunable-step text-to-image variant on SiliconFlow.",
	},
	"Bytedance/Z-Image-Turbo": {
		Ratio: 0, CompletionRatio: 1.0,
		Image: &adaptor.ImagePricingConfig{
			PricePerImageUsd: 0.005,
			MinImages:        1,
			DefaultSize:      "1024x1024",
		},
		InputModalities:  []string{"text"},
		OutputModalities: []string{"image"},
		Description:      "ByteDance Z-Image Turbo fast text-to-image generator on SiliconFlow.",
	},

	// === Audio models ===
	"FunAudioLLM/CosyVoice2-0.5B": {
		// SiliconFlow bills CosyVoice2 at $7.15 per 1M UTF-8 input bytes.
		// Approximate 1 token ≈ 4 UTF-8 bytes for English/Chinese mix → ~$0.029 / M tokens
		// expressed as audio prompt-token billing for accounting purposes.
		Audio: &adaptor.AudioPricingConfig{
			PromptRatio: (7.15 / 4.0) * ratio.MilliTokensUsd,
		},
		InputModalities:  []string{"text"},
		OutputModalities: []string{"audio"},
		HuggingFaceID:    "FunAudioLLM/CosyVoice2-0.5B",
		Description:      "Alibaba FunAudioLLM CosyVoice 2 0.5B multilingual TTS model on SiliconFlow.",
	},
}

// ModelList derived from ModelRatios for backward compatibility
var ModelList = adaptor.GetModelListFromPricing(ModelRatios)

// SiliconFlowToolingDefaults notes that SiliconFlow public docs focus on model usage; no separate tool fees are published (retrieved 2026-04-28).
// Source: https://siliconflow.cn/pricing
var SiliconFlowToolingDefaults = adaptor.ChannelToolConfig{}
