package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// zaiGLMModelRatios contains Z.AI GLM family entries served by Novita.
// GLM 4.x and 5.x are open-weight chat and vision-language models. Vision
// variants (4.5V, 4.6V) accept text+image input.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var zaiGLMModelRatios = map[string]adaptor.ModelConfig{
	"zai-org/autoglm-phone-9b-multilingual": {
		Ratio:                       0.035 * ratio.MilliTokensUsd,
		CompletionRatio:             3.94285714286,
		ContextLength:               65536,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/AutoGLM-Phone-9B-Multilingual",
		Description:                 "Z.AI AutoGLM Phone 9B multilingual on-device chat model with 64K context.",
	},
	"zai-org/glm-4.5-air": {
		Ratio:                       0.13 * ratio.MilliTokensUsd,
		CompletionRatio:             6.53846153846,
		CachedInputRatio:            0.025 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             98304,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5-Air",
		Description:                 "Z.AI GLM-4.5 Air efficient chat model with 128K context.",
	},
	"zai-org/glm-4.5": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.66666666667,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             98304,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5",
		Description:                 "Z.AI GLM-4.5 chat model with 128K context.",
	},
	"zai-org/glm-4.5v": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               65536,
		MaxOutputTokens:             16384,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5V",
		Description:                 "Z.AI GLM-4.5V vision-language chat model with 64K text+image context.",
	},
	"zai-org/glm-4.6": {
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.6",
		Description:                 "Z.AI GLM-4.6 chat model with 200K context.",
	},
	"zai-org/glm-4.6v": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.055 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.6V",
		Description:                 "Z.AI GLM-4.6V vision-language chat model with 128K text+image context.",
	},
	"zai-org/glm-4.7-flash": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             5.71428571429,
		CachedInputRatio:            0.01 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             128000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.7-Flash",
		Description:                 "Z.AI GLM-4.7 Flash efficient chat model with 200K context.",
	},
	"zai-org/glm-4.7": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.66666666667,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.7",
		Description:                 "Z.AI GLM-4.7 chat model with 200K context.",
	},
	"zai-org/glm-5.1": {
		// Novita repriced GLM-5.1 to $1.38/$4.40 with $0.26 cache-read effective May 2026.
		// Source: https://novita.ai/pricing (retrieved 2026-05-19)
		Ratio:                       1.38 * ratio.MilliTokensUsd,
		CompletionRatio:             4.40 / 1.38,
		CachedInputRatio:            0.26 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5.1",
		Description:                 "Z.AI GLM-5.1 chat model with 200K context.",
	},
	"zai-org/glm-5.2": {
		// Novita prices GLM-5.2 at $1.4/$4.40 with $0.26 cache-read.
		// Source: https://novita.ai/pricing (retrieved 2026-06-27)
		Ratio:                       1.4 * ratio.MilliTokensUsd,
		CompletionRatio:             4.40 / 1.4,
		CachedInputRatio:            0.26 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5.2",
		Description:                 "Z.AI GLM-5.2 reasoning chat model with 1M context.",
	},
	"zai-org/glm-5": {
		Ratio:                       1 * ratio.MilliTokensUsd,
		CompletionRatio:             3.2,
		CachedInputRatio:            0.2 * ratio.MilliTokensUsd,
		ContextLength:               202800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5",
		Description:                 "Z.AI GLM-5 chat model with 200K context.",
	},
	"zai-org/glm-5-turbo": {
		Ratio:                       1.20 * ratio.MilliTokensUsd,
		CompletionRatio:             4.00 / 1.20,
		CachedInputRatio:            0.24 * ratio.MilliTokensUsd,
		ContextLength:               202800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5-Turbo",
		Description:                 "Z.AI GLM-5 Turbo reasoning chat model with 200K context.",
	},
	"zai-org/glm-5v-turbo": {
		Ratio:                       1.20 * ratio.MilliTokensUsd,
		CompletionRatio:             4.00 / 1.20,
		CachedInputRatio:            0.24 * ratio.MilliTokensUsd, // cache-read $0.24/M
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5V-Turbo",
		Description:                 "Z.AI GLM-5V Turbo vision-language reasoning chat model with 200K context.",
	},
	"zai-org/glm-4.7-h": {
		Ratio:                       0.60 * ratio.MilliTokensUsd,
		CompletionRatio:             2.20 / 0.60,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.7-H",
		Description:                 "Z.AI GLM-4.7-H reasoning chat model with 200K context.",
	},
	"zai-org/glm-ocr": {
		Ratio:                       0.03 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-OCR",
		Description:                 "Z.AI GLM-OCR layout/parsing model accepting image input. Retired: absent from Novita's live serverless catalog and pricing page as of 2026-07-13.",
	},
}
