package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// qwenModelRatios contains Alibaba Qwen family entries served by Novita.
// The "fp8" suffix on Qwen3 dense/MoE rows reflects Novita's serving precision;
// VL variants advertise text+image input. Thinking variants use the restricted
// reasoning sampling parameter set.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var qwenModelRatios = map[string]adaptor.ModelConfig{
	"qwen/qwen-2.5-72b-instruct": {
		Ratio:                       0.38 * ratio.MilliTokensUsd,
		CompletionRatio:             1.05263157895,
		ContextLength:               32000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
		Description:                 "Alibaba Qwen 2.5 72B instruct chat model with 32K context.",
	},
	"qwen/qwen2.5-7b-instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
		Description:                 "Alibaba Qwen 2.5 7B instruct chat model with 32K context.",
	},
	"qwen/qwen2.5-vl-72b-instruct": {
		Ratio:                       0.8 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
		Description:                 "Qwen 2.5 vision-language 72B instruct model with text+image input and 32K context.",
	},
	"qwen/qwen3-235b-a22b-fp8": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B",
		Description:                 "Qwen3 235B/A22B MoE chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-235b-a22b-instruct-2507": {
		Ratio:                       0.09 * ratio.MilliTokensUsd,
		CompletionRatio:             6.44444444444,
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Description:                 "Qwen3 235B/A22B Instruct 2507 with 128K context.",
	},
	"qwen/qwen3-235b-a22b-thinking-2507": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
		Description:                 "Qwen3 235B/A22B Thinking 2507 reasoning chat model with 128K context.",
	},
	"qwen/qwen3-30b-a3b-fp8": {
		Ratio:                       0.09 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
		Description:                 "Qwen3 30B/A3B MoE chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-32b-fp8": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.5,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-32B",
		Description:                 "Qwen3 32B dense chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-4b-fp8": {
		Ratio:                       0.03 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               128000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-4B",
		Description:                 "Qwen3 4B compact chat model served at FP8 with 128K context.",
	},
	"qwen/qwen3-coder-30b-a3b-instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             3.85714285714,
		ContextLength:               160000,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
		Description:                 "Qwen3 Coder 30B/A3B Instruct MoE coding chat model with 160K context.",
	},
	"qwen/qwen3-coder-480b-a35b-instruct": {
		// Novita repriced Qwen3-Coder-480B to $0.38/$1.55 effective May 2026.
		// Source: https://novita.ai/pricing (retrieved 2026-05-19)
		Ratio:                       0.38 * ratio.MilliTokensUsd,
		CompletionRatio:             1.55 / 0.38,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		Description:                 "Qwen3 Coder 480B/A35B Instruct flagship coding chat model with 256K context.",
	},
	"qwen/qwen3-coder-next": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             7.5,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Qwen3 Coder Next preview coding chat model with 256K context.",
	},
	"qwen/qwen3-next-80b-a3b-instruct": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
		Description:                 "Qwen3 Next 80B/A3B Instruct MoE chat model with 128K context.",
	},
	"qwen/qwen3-next-80b-a3b-thinking": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
		Description:                 "Qwen3 Next 80B/A3B Thinking MoE reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-235b-a22b-instruct": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
		Description:                 "Qwen3 VL 235B/A22B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen3-vl-235b-a22b-thinking": {
		Ratio:                       0.98 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0306122449,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
		Description:                 "Qwen3 VL 235B/A22B vision-language reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-30b-a3b-instruct": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             3.5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
		Description:                 "Qwen3 VL 30B/A3B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen3-vl-30b-a3b-thinking": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
		Description:                 "Qwen3 VL 30B/A3B vision-language reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-8b-instruct": {
		Ratio:                       0.08 * ratio.MilliTokensUsd,
		CompletionRatio:             6.25,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
		Description:                 "Qwen3 VL 8B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen-mt-plus": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		ContextLength:               16384,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Qwen MT Plus translation-tuned chat model with 16K context.",
	},
	"qwen/qwen3.5-122b-a10b": {
		Ratio:                       0.4 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
		Description:                 "Qwen3.5 122B/A10B MoE chat model with 256K context.",
	},
	"qwen/qwen3.5-27b": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-27B",
		Description:                 "Qwen3.5 27B dense chat model with 256K context.",
	},
	"qwen/qwen3.5-35b-a3b": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
		Description:                 "Qwen3.5 35B/A3B MoE chat model with 256K context.",
	},
	"qwen/qwen3.5-397b-a17b": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             6,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
		Description:                 "Qwen3.5 397B/A17B MoE flagship chat model with 256K context.",
	},
	"qwen/qwen3-max": {
		// Novita bills qwen3-max with three input-token tiers; the base struct holds
		// tier 1 (input<=32768) and Tiers holds tiers 2 and 3.
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-07-13)
		Ratio:           0.845 * ratio.MilliTokensUsd,
		CompletionRatio: 3.38 / 0.845, // =4.0
		Tiers: []adaptor.ModelRatioTier{
			{
				// tier 2: 32768 < input <= 131072 ($1.40/$5.64)
				Ratio:               1.40 * ratio.MilliTokensUsd,
				CompletionRatio:     5.64 / 1.40, // =4.0286
				InputTokenThreshold: 32768,
			},
			{
				// tier 3: 131072 < input <= 258048 ($2.11/$8.45)
				Ratio:               2.11 * ratio.MilliTokensUsd,
				CompletionRatio:     8.45 / 2.11, // =4.0047
				InputTokenThreshold: 131072,
			},
		},
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Alibaba Qwen3 Max flagship chat model with 256K context and tiered pricing.",
	},
	"qwen/qwen3.7-max": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             3.75 / 1.25,
		CachedInputRatio:            0.25 * ratio.MilliTokensUsd,
		ContextLength:               1000000,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Alibaba Qwen3.7 Max flagship reasoning chat model with 1M context.",
	},
	"qwen/qwen3.6-27b": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.6 / 0.6,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.6-27B",
		Description:                 "Qwen3.6 27B multimodal reasoning chat model with 256K context.",
	},
	"qwen/qwen3.6-35b-a3b": {
		Ratio:                       0.248 * ratio.MilliTokensUsd,
		CompletionRatio:             1.485 / 0.248,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
		Description:                 "Qwen3.6 35B/A3B MoE multimodal reasoning chat model with 256K context.",
	},
	"qwen/qwen3-omni-30b-a3b-instruct": {
		// LIMITATION: Novita prices this omni model per input modality (text $0.25/M,
		// image/video $0.46/M, audio $2.20/M ~9x text). The single Ratio field can only
		// encode the text rate, so audio/image/video input is under-billed here.
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-07-13)
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             0.97 / 0.25,
		ContextLength:               65536,
		MaxOutputTokens:             16384,
		InputModalities:             novitaOmniInModalities,
		OutputModalities:            novitaTextAudioOutModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Omni-30B-A3B-Instruct",
		Description:                 "Qwen3 Omni 30B/A3B omnimodal (text/image/audio/video) instruct chat model with 64K context.",
	},
	"qwen/qwen3-omni-30b-a3b-thinking": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             0.97 / 0.25,
		ContextLength:               65536,
		MaxOutputTokens:             16384,
		InputModalities:             novitaOmniInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Omni-30B-A3B-Thinking",
		Description:                 "Qwen3 Omni 30B/A3B omnimodal (text/image/audio/video) reasoning chat model with 64K context.",
	},
}
