package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// miscModelRatios contains lower-volume Novita model families: Inclusion AI Ling,
// KwaiPilot, Microsoft, MiniMax, Mistral, MoonshotAI Kimi, NousResearch, OpenAI
// GPT-OSS, Sao10K Llama fine-tunes, Xiaomi MiMo, plus the Novita-internal
// "elephant" alias. MiniMax M-series weights are not released, so HuggingFaceID
// is intentionally left empty for those rows.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var miscModelRatios = map[string]adaptor.ModelConfig{
	// Internal/branded alias without a HuggingFace card. Capability set follows
	// Novita's documented OpenAI-compatible chat surface.
	"elephant": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Novita-branded chat alias (parameters tracked via Novita pricing page).",
	},

	// Inclusion AI Ling — open-weight efficient MoE chat model.
	"inclusionai/ling-2.6-flash": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "inclusionAI/Ling-flash-2.0",
		Description:                 "Inclusion AI Ling 2.6 Flash MoE chat model with 256K context.",
	},
	"inclusionai/ling-2.6-1t": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             2.5 / 0.3,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "inclusionAI/Ling-1T",
		Description:                 "Inclusion AI Ling 2.6 1T MoE chat model with 256K context.",
	},
	"inclusionai/ring-2.6-1t": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             2.5 / 0.3,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "inclusionAI/Ring-1T",
		Description:                 "Inclusion AI Ring 2.6 1T MoE reasoning chat model with 256K context.",
	},

	// KwaiPilot KAT-Coder Pro — coding-focused chat model.
	"kwaipilot/kat-coder-pro": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.06 * ratio.MilliTokensUsd,
		ContextLength:               256000,
		MaxOutputTokens:             128000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Kwaipilot/KAT-Coder-Pro-V1",
		Description:                 "KwaiPilot KAT-Coder Pro coding chat model with 256K context.",
	},

	// Microsoft WizardLM — Mixtral 8x22B fine-tune. Treated as text-only chat.
	"microsoft/wizardlm-2-8x22b": {
		Ratio:                       0.62 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               65535,
		MaxOutputTokens:             8000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "microsoft/WizardLM-2-8x22B",
		Description:                 "Microsoft WizardLM 2 8x22B Mixtral fine-tune with 64K context.",
	},

	// MiniMax M-series — closed-source style chat aliases hosted by Novita. The
	// upstream weights are not released, so HuggingFaceID is intentionally omitted.
	"minimax/minimax-m2.1": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.1 chat model with 200K context.",
	},
	"minimax/minimax-m2.5-highspeed": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131100,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Throughput-optimised MiniMax M2.5 with 200K context.",
	},
	"minimax/minimax-m2.5": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131100,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.5 chat model with 200K context.",
	},
	"minimax/minimax-m2.7": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.06 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.7 chat model with 200K context.",
	},
	"minimax/minimax-m2": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2 chat model with 200K context.",
	},
	"minimax/minimax-m2.7-highspeed": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             2.4 / 0.6,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Throughput-optimised MiniMax M2.7 with 200K context.",
	},
	"minimax/minimax-m3": {
		// Novita bills minimax-m3 with two input-token tiers; the base struct holds
		// tier 1 (<=512K tokens) and Tiers holds tier 2 (>512K tokens).
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-06-13)
		Ratio:            0.30 * ratio.MilliTokensUsd,
		CompletionRatio:  1.20 / 0.30,
		CachedInputRatio: 0.06 * ratio.MilliTokensUsd,
		Tiers: []adaptor.ModelRatioTier{
			{
				Ratio:               0.60 * ratio.MilliTokensUsd,
				CompletionRatio:     2.40 / 0.60,
				CachedInputRatio:    0.12 * ratio.MilliTokensUsd,
				InputTokenThreshold: 524288,
			},
		},
		ContextLength:               1000000,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M3 multimodal reasoning chat model with 1M context and tiered pricing.",
	},
	"minimaxai/minimax-m1-80k": {
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		ContextLength:               1000000,
		MaxOutputTokens:             40000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		HuggingFaceID:               "MiniMaxAI/MiniMax-M1-80k",
		Description:                 "MiniMax M1 80K open-weight chat model with 1M context.",
	},

	// Mistral Nemo — open-weight 12B chat model.
	"mistralai/mistral-nemo": {
		Ratio:                       0.04 * ratio.MilliTokensUsd,
		CompletionRatio:             4.25,
		ContextLength:               60288,
		MaxOutputTokens:             16000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "mistralai/Mistral-Nemo-Instruct-2407",
		Description:                 "Mistral Nemo instruct 12B chat model with ~60K context.",
	},

	// MoonshotAI Kimi K2 family — open-weight long-context chat models.
	"moonshotai/kimi-k2-0905": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4.16666666667,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
		Description:                 "Moonshot Kimi K2 0905 instruct chat model with 256K context.",
	},
	"moonshotai/kimi-k2-instruct": {
		Ratio:                       0.57 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0350877193,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
		Description:                 "Moonshot Kimi K2 instruct chat model with 128K context.",
	},
	"moonshotai/kimi-k2-thinking": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4.16666666667,
		CachedInputRatio:            0.15 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
		Description:                 "Moonshot Kimi K2 Thinking reasoning chat model with 256K context.",
	},
	"moonshotai/kimi-k2.5": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		CachedInputRatio:            0.1 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.5",
		Description:                 "Moonshot Kimi K2.5 chat model with 256K context.",
	},
	"moonshotai/kimi-k2.6": {
		// Novita repriced Kimi K2.6 to $0.80/$3.40 with $0.16 cache-read effective May 2026.
		// Source: https://novita.ai/pricing (retrieved 2026-05-19)
		Ratio:                       0.80 * ratio.MilliTokensUsd,
		CompletionRatio:             3.40 / 0.80,
		CachedInputRatio:            0.16 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.6",
		Description:                 "Moonshot Kimi K2.6 chat model with 256K context.",
	},
	"moonshotai/kimi-k2.7-code": {
		Ratio:                       0.95 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0 / 0.95,
		CachedInputRatio:            0.19 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
		Description:                 "Moonshot Kimi K2.7 Code multimodal reasoning coding chat model with 256K context.",
	},

	// NousResearch Hermes 2 Pro — Llama 3 8B fine-tune with strong tool calling.
	"nousresearch/hermes-2-pro-llama-3-8b": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "NousResearch/Hermes-2-Pro-Llama-3-8B",
		Description:                 "NousResearch Hermes 2 Pro Llama 3 8B chat model with strong function calling.",
	},

	// OpenAI GPT-OSS family — open-weight Apache-2.0 reasoning chat models.
	"openai/gpt-oss-120b": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		// Novita documents GPT-OSS reasoning_effort ("low"/"medium"/"high") through its
		// OpenAI-compatible REST surface.
		// Source: https://medium.com/@marketing_novita.ai/gpt-oss-on-novita-ai-access-openais-open-source-models-via-api-b62c87f378a0
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
		DefaultReasoningEffort:    "medium",
		Quantization:              "bf16",
		HuggingFaceID:             "openai/gpt-oss-120b",
		Description:               "OpenAI GPT-OSS 120B open-weight reasoning chat model with 128K context.",
	},
	"openai/gpt-oss-20b": {
		Ratio:                       0.04 * ratio.MilliTokensUsd,
		CompletionRatio:             3.75,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		// Novita documents GPT-OSS reasoning_effort ("low"/"medium"/"high") through its
		// OpenAI-compatible REST surface.
		// Source: https://medium.com/@marketing_novita.ai/gpt-oss-on-novita-ai-access-openais-open-source-models-via-api-b62c87f378a0
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
		DefaultReasoningEffort:    "medium",
		Quantization:              "bf16",
		HuggingFaceID:             "openai/gpt-oss-20b",
		Description:               "OpenAI GPT-OSS 20B open-weight reasoning chat model with 128K context.",
	},

	// Sao10K Llama fine-tunes — community role-play models.
	"Sao10K/L3-8B-Stheno-v3.2": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             32000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3-8B-Stheno-v3.2",
		Description:                 "Sao10K Llama 3 8B Stheno v3.2 community role-play fine-tune.",
	},
	"sao10k/l31-70b-euryale-v2.2": {
		Ratio:                       1.48 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3.1-70B-Euryale-v2.2",
		Description:                 "Sao10K Llama 3.1 70B Euryale v2.2 community role-play fine-tune.",
	},
	"sao10k/l3-8b-lunaris": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3-8B-Lunaris-v1",
		Description:                 "Sao10K Llama 3 8B Lunaris community role-play fine-tune.",
	},

	// StepFun Step — open-weight vision-language MoE reasoning chat model.
	"stepfun/step-3.7-flash": {
		// Novita prices Step 3.7 Flash at $0.2/$1.15 with $0.04 cache-read.
		// Source: https://novita.ai/pricing (retrieved 2026-06-27)
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             1.15 / 0.2,
		CachedInputRatio:            0.04 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             256000,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		SupportedReasoningEfforts:   []string{"low", "medium", "high"},
		DefaultReasoningEffort:      "medium",
		Quantization:                "fp8",
		HuggingFaceID:               "stepfun-ai/Step-3.7-Flash",
		Description:                 "StepFun Step 3.7 Flash 196B/A11B vision-language MoE reasoning chat model with 256K context.",
	},

	// Xiaomi MiMo — small efficient chat model.
	"xiaomimimo/mimo-v2-flash": {
		// Novita repriced MiMo V2 Flash to $0.11/$0.33 with $0.024 cache-read.
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-06-13)
		Ratio:                       0.11 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.024 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "XiaomiMiMo/MiMo-V2-Flash",
		Description:                 "Xiaomi MiMo V2 Flash chat model with 256K context.",
	},
	"xiaomimimo/mimo-v2.5": {
		Ratio:                       0.168 * ratio.MilliTokensUsd,
		CompletionRatio:             0.336 / 0.168,
		CachedInputRatio:            0.0034 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextImageVideoInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5",
		Description:                 "Xiaomi MiMo V2.5 multimodal reasoning chat model with 1M context.",
	},
	"xiaomimimo/mimo-v2.5-pro": {
		Ratio:                       0.522 * ratio.MilliTokensUsd,
		CompletionRatio:             1.044 / 0.522,
		CachedInputRatio:            0.0043 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5-Pro",
		Description:                 "Xiaomi MiMo V2.5 Pro reasoning chat model with 1M context.",
	},

	// NVIDIA Nemotron — open-weight efficient reasoning chat model.
	"nvidia/nemotron-3-nano-30b-a3b": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             0.20 / 0.05,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B",
		Description:                 "NVIDIA Nemotron 3 Nano 30B/A3B reasoning chat model with 128K context.",
	},

	// THUDM GLM-4 0414 — open-weight chat model (distinct from Z.AI GLM lineage).
	"thudm/glm-4-32b-0414": {
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             1.66 / 0.55,
		ContextLength:               32768,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "THUDM/GLM-4-32B-0414",
		Description:                 "THUDM GLM-4 32B 0414 chat model with 32K context.",
	},

	// Baichuan medical-tuned chat model.
	"baichuan/baichuan-m2-32b": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "baichuan-inc/Baichuan-M2-32B",
		Description:                 "Baichuan M2 32B chat model with 32K context.",
	},

	// PaddlePaddle PaddleOCR-VL — OCR layout/parsing vision model.
	"paddlepaddle/paddleocr-vl": {
		Ratio:                       0.02 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "PaddlePaddle/PaddleOCR-VL",
		Description:                 "PaddlePaddle PaddleOCR-VL OCR layout/parsing model accepting image input.",
	},
}
