package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// deepseekModelRatios contains DeepSeek family entries served by Novita.
// DeepSeek V3.x and R1 lineage are open-weight MoE models; Novita typically
// serves them at FP8 precision. Reasoning variants (R1, V4 thinking, prover)
// use the restricted reasoning sampling parameter set.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var deepseekModelRatios = map[string]adaptor.ModelConfig{
	"deepseek/deepseek-ocr": {
		Ratio:                       0.03 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "deepseek-ai/DeepSeek-OCR",
		Description:                 "DeepSeek-OCR layout/parsing model accepting image input with 8K context.",
	},
	"deepseek/deepseek-ocr-2": {
		Ratio:                       0.03 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "deepseek-ai/DeepSeek-OCR",
		Description:                 "DeepSeek-OCR v2 layout/parsing model accepting image input with 8K context.",
	},
	"deepseek/deepseek-prover-v2-671b": {
		Ratio:                       0.7 * ratio.MilliTokensUsd,
		CompletionRatio:             3.57142857143,
		ContextLength:               160000,
		MaxOutputTokens:             160000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-Prover-V2-671B",
		Description:                 "DeepSeek Prover V2 671B specialised theorem-proving reasoning model with 160K context.",
	},
	"deepseek/deepseek-r1-0528": {
		Ratio:                       0.7 * ratio.MilliTokensUsd,
		CompletionRatio:             3.57142857143,
		CachedInputRatio:            0.35 * ratio.MilliTokensUsd,
		ContextLength:               163840,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528",
		Description:                 "DeepSeek R1 0528 reasoning model with 160K context and cache-read discount.",
	},
	"deepseek/deepseek-r1-0528-qwen3-8b": {
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-07-13)
		Ratio:                       0.06 * ratio.MilliTokensUsd,
		CompletionRatio:             0.09 / 0.06, // =1.5
		ContextLength:               128000,
		MaxOutputTokens:             32000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
		Description:                 "DeepSeek R1 0528 reasoning distilled into Qwen3 8B with 128K context.",
	},
	"deepseek/deepseek-r1-distill-llama-70b": {
		Ratio:                       0.8 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningOnlyFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
		Description:                 "DeepSeek R1 reasoning distilled into Llama 3 70B; 8K context.",
	},
	"deepseek/deepseek-r1-turbo": {
		Ratio:                       0.7 * ratio.MilliTokensUsd,
		CompletionRatio:             3.57142857143,
		ContextLength:               64000,
		MaxOutputTokens:             16000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-R1",
		Description:                 "Throughput-optimised DeepSeek R1 (Turbo) with 64K context.",
	},
	"deepseek/deepseek-v3-0324": {
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             4.14814814815,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               163840,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3-0324",
		Description:                 "DeepSeek V3 0324 chat model with 160K context and cache-read discount.",
	},
	"deepseek/deepseek-v3.1": {
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             3.7037037037,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
		Description:                 "DeepSeek V3.1 chat model with 128K context and cache-read discount.",
	},
	"deepseek/deepseek-v3.1-terminus": {
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             3.7037037037,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1-Terminus",
		Description:                 "DeepSeek V3.1 Terminus refresh with 128K context.",
	},
	"deepseek/deepseek-v3.2-exp": {
		Ratio:                       0.27 * ratio.MilliTokensUsd,
		CompletionRatio:             1.51851851852,
		ContextLength:               163840,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
		Description:                 "Experimental DeepSeek V3.2 with 160K context.",
	},
	"deepseek/deepseek-v3.2": {
		Ratio:                       0.269 * ratio.MilliTokensUsd,
		CompletionRatio:             1.48698884758,
		CachedInputRatio:            0.1345 * ratio.MilliTokensUsd,
		ContextLength:               163840,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
		Description:                 "DeepSeek V3.2 chat model with 160K context and cache-read discount.",
	},
	"deepseek/deepseek-v3-turbo": {
		Ratio:                       0.4 * ratio.MilliTokensUsd,
		CompletionRatio:             3.25,
		ContextLength:               64000,
		MaxOutputTokens:             16000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V3",
		Description:                 "Throughput-optimised DeepSeek V3 (Turbo) with 64K context.",
	},
	"deepseek/deepseek-v4-flash": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             2,
		CachedInputRatio:            0.028 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             393216,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
		Description:                 "DeepSeek V4 Flash with 1M context, fast cache-read discount and reasoning support.",
	},
	"deepseek/deepseek-v4-pro": {
		// Novita repriced DeepSeek-V4-Pro to $1.60/$3.20 with $0.135 cache-read effective May 2026.
		// Source: https://api.novita.ai/v3/openai/models (retrieved 2026-06-13)
		Ratio:                       1.60 * ratio.MilliTokensUsd,
		CompletionRatio:             3.20 / 1.60,
		CachedInputRatio:            0.135 * ratio.MilliTokensUsd,
		ContextLength:               1048576,
		MaxOutputTokens:             393216,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
		Description:                 "DeepSeek V4 Pro flagship with 1M context and reasoning support.",
	},
}
