package fireworks

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// embeddingModels contains Qwen3 embedding plus legacy BERT-style embedding
// models hosted by Fireworks. Priced per 1M input tokens — CompletionRatio is
// kept at 1.0 for compatibility with the shared billing model.
var embeddingModels = map[string]adaptor.ModelConfig{
	// Qwen3 embedding family — $0.10/1M (8B), $0.016/1M (4B), $0.008/1M (0.6B).
	"accounts/fireworks/models/qwen3-embedding-8b": {
		Ratio:                       0.10 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               32768,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "Qwen/Qwen3-Embedding-8B",
		Description:                 "Alibaba Qwen3 Embedding 8B dense embedding model (4096-dim) with 32K context.",
	},
	"accounts/fireworks/models/qwen3-embedding-4b": {
		Ratio:                       0.016 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               32768,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "Qwen/Qwen3-Embedding-4B",
		Description:                 "Alibaba Qwen3 Embedding 4B mid-size dense embedding model with 32K context. Retired from Fireworks serverless (confirmed via model card, 2026-07-13); on-demand/dedicated only.",
	},
	"accounts/fireworks/models/qwen3-embedding-0p6b": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               32768,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "Qwen/Qwen3-Embedding-0.6B",
		Description:                 "Alibaba Qwen3 Embedding 0.6B compact dense embedding model for low-latency retrieval. Retired from Fireworks serverless (confirmed via model card, 2026-07-13); on-demand/dedicated only.",
	},
	// Legacy BERT-style embeddings — <150M = $0.008/1M, 150-350M = $0.016/1M.
	"nomic-ai/nomic-embed-text-v1.5": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               8192,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "nomic-ai/nomic-embed-text-v1.5",
		Description:                 "Nomic Embed Text v1.5 (137M, 8192 context) Matryoshka-trained embedding model.",
	},
	"nomic-ai/nomic-embed-text-v1": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               8192,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "nomic-ai/nomic-embed-text-v1",
		Description:                 "Nomic Embed Text v1 (137M, 8192 context) general-purpose embedding model.",
	},
	"WhereIsAI/UAE-Large-V1": {
		Ratio:                       0.016 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "WhereIsAI/UAE-Large-V1",
		Description:                 "WhereIsAI UAE-Large-V1 BERT-large (335M) embedding model tuned via AnglE loss for retrieval.",
	},
	"thenlper/gte-large": {
		Ratio:                       0.016 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "thenlper/gte-large",
		Description:                 "Alibaba GTE-Large (335M) general text embedding model for retrieval and similarity tasks.",
	},
	"thenlper/gte-base": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "thenlper/gte-base",
		Description:                 "Alibaba GTE-Base (110M) general text embedding model for retrieval and similarity tasks.",
	},
	"BAAI/bge-base-en-v1.5": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "BAAI/bge-base-en-v1.5",
		Description:                 "BAAI BGE base English v1.5 (110M) BERT-based embedding model for retrieval.",
	},
	"BAAI/bge-small-en-v1.5": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "BAAI/bge-small-en-v1.5",
		Description:                 "BAAI BGE small English v1.5 (33M) compact BERT embedding model for low-latency retrieval.",
	},
	"mixedbread-ai/mxbai-embed-large-v1": {
		Ratio:                       0.016 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "mixedbread-ai/mxbai-embed-large-v1",
		Description:                 "Mixedbread mxbai-embed-large-v1 (335M) BERT-large embedding model trained with contrastive loss.",
	},
	"sentence-transformers/all-MiniLM-L6-v2": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "sentence-transformers/all-MiniLM-L6-v2",
		Description:                 "Sentence-Transformers all-MiniLM-L6-v2 (22M) compact embedding model widely used as retrieval baseline.",
	},
	"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": {
		Ratio:                       0.008 * ratio.MilliTokensUsd,
		CompletionRatio:             1.0,
		ContextLength:               512,
		InputModalities:             fwTextOnlyModalities,
		OutputModalities:            fwTextOnlyModalities,
		SupportedSamplingParameters: fwEmbedSamplingParams,
		Quantization:                "fp16",
		HuggingFaceID:               "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
		Description:                 "Sentence-Transformers paraphrase-multilingual-MiniLM-L12-v2 (118M) covering 50+ languages for retrieval.",
	},
}
